import type { MenuSection, VenueMenuData, PlaceholderKind, FoodPairing, Pairing } from './menu-data'
import { applyPlaceholders, applyCoffeeTastes } from './menu-data'

// ---------------------------------------------------------------------------
// Amour Pasticeri — Durrës, Plazh. Prices in Albanian Lek (ALL / L).
// Source: owner CSV + fridge photos, parsed 2026-07-26. en seeded; sq/it additive.
// Dessert items share the engraving placeholder until real photos arrive.
// ---------------------------------------------------------------------------

const PH = '/venue-assets/amour/dessert-placeholder.png'
const COFFEE_PH = '/venue-assets/amour/coffee-placeholder.png'
const COFFEE_WATER_PH = '/venue-assets/amour/coffee-water-placeholder.png'
const FRUIT_PH = '/venue-assets/amour/fruit-placeholder.png'
const CAKE_SLICE_PH = '/venue-assets/amour/cake-slice-placeholder.png'

// Placeholder illustration per kind — filled into items via applyPlaceholders() below.
// Real photo always wins; only items with no photo fall back to these by their `ph`.
const PLACEHOLDERS: Partial<Record<PlaceholderKind, string>> = {
  coffee: COFFEE_PH,               // plain cup — most hot drinks
  'coffee-water': COFFEE_WATER_PH, // cup + water — espresso & americano only
  fruit: FRUIT_PH,  // apple engraving — generic fruit-dessert placeholder
  'cake-slice': CAKE_SLICE_PH, // berry-glaze slice engraving
  eclair: PH,       // [TODO] eclair engraving
  dessert: PH,
  drink: PH,        // [TODO] drink engraving
}

// ── DRINKS ── (sections → left category tab) ────────────────────────────────

const coffee: MenuSection = {
  key: 'hot-drinks',
  type: 'cocktail',
  i18n: {
    en: { label: 'Coffee', note: 'We serve espresso and americano with water.' },
    sq: { label: 'Kafe',   note: 'Espresson dhe amerikanon i shërbejmë me ujë.' },
    it: { label: 'Caffè',  note: 'Serviamo espresso e americano con acqua.' },
    pl: { label: 'Kawa',   note: 'Espresso i americano podajemy z wodą.' },
    uk: { label: 'Кава',   note: 'Еспресо й американо подаємо з водою.' },
    de: { label: 'Kaffee', note: 'Espresso und Americano servieren wir mit Wasser.' },
    fr: { label: 'Café',   note: "Nous servons l'espresso et l'americano avec de l'eau." },
    no: { label: 'Kaffe',  note: 'Vi serverer espresso og americano med vann.' },
  },
  items: [
    { id: 'cappuccino',     slug: 'cappuccino',     price: '150', posterSrc: '/venue-assets/amour/cappuccino.jpg', coffee: 'cappuccino',
      i18n: {
        en: { name: 'Cappuccino', desc: 'Espresso, steamed milk and foam, one third each.' },
        sq: { name: 'Cappuccino', desc: 'Espresso, qumësht i avulluar dhe shkumë, nga një e treta secila.' },
        it: { name: 'Cappuccino', desc: 'Espresso, latte montato e schiuma, un terzo ciascuno.' },
        pl: { name: 'Cappuccino', desc: 'Espresso, spienione mleko i pianka, po jednej trzeciej.' },
        uk: { name: 'Cappuccino', desc: 'Еспресо, парне молоко й піна, по третині кожного.' },
        de: { name: 'Cappuccino', desc: 'Espresso, aufgeschäumte Milch und Schaum, je ein Drittel.' },
        fr: { name: 'Cappuccino', desc: 'Espresso, lait vapeur et mousse, un tiers chacun.' },
        no: { name: 'Cappuccino', desc: 'Espresso, dampet melk og skum, en tredjedel av hver.' },
      } },
    { id: 'espresso',       slug: 'espresso',       price: '80', ph: 'coffee-water', coffee: 'espresso',
      i18n: {
        en: { name: 'Espresso', desc: '30 ml, brewed under high pressure.', note: 'Served with a glass of water.' },
        sq: { name: 'Espresso', desc: '30 ml, i përgatitur nën presion të lartë.', note: 'Shërbehet me një gotë ujë.' },
        it: { name: 'Espresso', desc: '30 ml, estratto ad alta pressione.', note: "Servito con un bicchiere d'acqua." },
        pl: { name: 'Espresso', desc: '30 ml, parzone pod wysokim ciśnieniem.', note: 'Podawane ze szklanką wody.' },
        uk: { name: 'Espresso', desc: '30 мл, приготоване під високим тиском.', note: 'Подається зі склянкою води.' },
        de: { name: 'Espresso', desc: '30 ml, unter hohem Druck gebrüht.', note: 'Wird mit einem Glas Wasser serviert.' },
        fr: { name: 'Espresso', desc: '30 ml, extrait sous haute pression.', note: "Servi avec un verre d'eau." },
        no: { name: 'Espresso', desc: '30 ml, brygget under høyt trykk.', note: 'Serveres med et glass vann.' },
      } },
    { id: 'americano',      slug: 'americano',      price: '90', posterSrc: '/venue-assets/amour/americano.png', coffee: 'americano',
      i18n: {
        en: { name: 'Americano', desc: 'Espresso topped up with hot water.', note: 'Served with a glass of water.' },
        sq: { name: 'Americano', desc: 'Espresso i mbushur me ujë të nxehtë.', note: 'Shërbehet me një gotë ujë.' },
        it: { name: 'Americano', desc: 'Espresso allungato con acqua calda.', note: "Servito con un bicchiere d'acqua." },
        pl: { name: 'Americano', desc: 'Espresso dopełnione gorącą wodą.', note: 'Podawane ze szklanką wody.' },
        uk: { name: 'Americano', desc: 'Еспресо, доповнене гарячою водою.', note: 'Подається зі склянкою води.' },
        de: { name: 'Americano', desc: 'Espresso mit heißem Wasser aufgefüllt.', note: 'Wird mit einem Glas Wasser serviert.' },
        fr: { name: 'Americano', desc: "Espresso allongé à l'eau chaude.", note: "Servi avec un verre d'eau." },
        no: { name: 'Americano', desc: 'Espresso fylt opp med varmt vann.', note: 'Serveres med et glass vann.' },
      } },
    { id: 'ice-coffee',     slug: 'ice-coffee',     price: '150', ph: 'coffee', coffee: 'ice-coffee',
      i18n: {
        en: { name: 'Ice Coffee', desc: 'Espresso poured over ice.' },
        sq: { name: 'Ice Coffee', desc: 'Espresso i derdhur mbi akull.' },
        it: { name: 'Ice Coffee', desc: 'Espresso versato sul ghiaccio.' },
        pl: { name: 'Ice Coffee', desc: 'Espresso zalane lodem.' },
        uk: { name: 'Ice Coffee', desc: 'Еспресо, залите на лід.' },
        de: { name: 'Ice Coffee', desc: 'Espresso über Eis gegossen.' },
        fr: { name: 'Ice Coffee', desc: 'Espresso versé sur de la glace.' },
        no: { name: 'Ice Coffee', desc: 'Espresso helt over is.' },
      } },
    { id: 'macchiato',      slug: 'macchiato',      price: '90', ph: 'coffee', coffee: 'macchiato',
      sizes: [{ label: 'S', price: '90' }, { label: 'M', price: '150' }],
      i18n: {
        en: { name: 'Macchiato', desc: 'Espresso marked with a spoonful of milk foam.' },
        sq: { name: 'Macchiato', desc: 'Espresso i shënuar me një lugë shkumë qumështi.' },
        it: { name: 'Macchiato', desc: 'Espresso macchiato con un cucchiaio di schiuma di latte.' },
        pl: { name: 'Macchiato', desc: 'Espresso z łyżką mlecznej pianki.' },
        uk: { name: 'Macchiato', desc: 'Еспресо з ложкою молочної піни.' },
        de: { name: 'Macchiato', desc: 'Espresso mit einem Löffel Milchschaum.' },
        fr: { name: 'Macchiato', desc: "Espresso taché d'une cuillère de mousse de lait." },
        no: { name: 'Macchiato', desc: 'Espresso med en skje melkeskum.' },
      } },
    { id: 'hot-chocolate',  slug: 'hot-chocolate',  price: '150', ph: 'coffee', coffee: 'hot-chocolate',
      i18n: {
        en: { name: 'Hot Chocolate',  desc: 'Melted chocolate with milk.' },
        sq: { name: 'Hot Chocolate',  desc: 'Çokollatë e shkrirë me qumësht.' },
        it: { name: 'Hot Chocolate',  desc: 'Cioccolato fuso con latte.' },
        pl: { name: 'Hot Chocolate',  desc: 'Roztopiona czekolada z mlekiem.' },
        uk: { name: 'Hot Chocolate', desc: 'Розтоплений шоколад з молоком.' },
        de: { name: 'Hot Chocolate',  desc: 'Geschmolzene Schokolade mit Milch.' },
        fr: { name: 'Hot Chocolate',  desc: 'Chocolat fondu au lait.' },
        no: { name: 'Hot Chocolate',  desc: 'Smeltet sjokolade med melk.' },
      } },
    { id: 'cold-chocolate', slug: 'cold-chocolate', price: '150', ph: 'coffee', coffee: 'cold-chocolate',
      i18n: {
        en: { name: 'Cold Chocolate',  desc: 'Cold chocolate with milk, over ice.' },
        sq: { name: 'Cold Chocolate',  desc: 'Çokollatë e ftohtë me qumësht, mbi akull.' },
        it: { name: 'Cold Chocolate',  desc: 'Cioccolato freddo con latte, sul ghiaccio.' },
        pl: { name: 'Cold Chocolate',  desc: 'Zimna czekolada z mlekiem, z lodem.' },
        uk: { name: 'Cold Chocolate', desc: 'Холодний шоколад з молоком, на льоду.' },
        de: { name: 'Cold Chocolate',  desc: 'Kalte Schokolade mit Milch, auf Eis.' },
        fr: { name: 'Cold Chocolate',  desc: 'Chocolat froid au lait, sur glace.' },
        no: { name: 'Cold Chocolate',  desc: 'Kald sjokolade med melk, på is.' },
      } },
    { id: 'nescafe',        slug: 'nescafe',        price: '150', ph: 'coffee', coffee: 'nescafe',
      i18n: {
        en: { name: 'Nescafé', desc: 'Instant coffee.' },
        sq: { name: 'Nescafé', desc: 'Kafe e çastit.' },
        it: { name: 'Nescafé', desc: 'Caffè solubile.' },
        pl: { name: 'Nescafé', desc: 'Kawa rozpuszczalna.' },
        uk: { name: 'Nescafé', desc: 'Розчинна кава.' },
        de: { name: 'Nescafé', desc: 'Löslicher Kaffee.' },
        fr: { name: 'Nescafé', desc: 'Café soluble.' },
        no: { name: 'Nescafé', desc: 'Pulverkaffe.' },
      } },
  ],
}

const drinks: MenuSection = {
  key: 'soft-drinks',
  type: 'cocktail',
  views: ['list'],
  i18n: {
    en: { label: 'Drinks' },
    sq: { label: 'Pije' },
    it: { label: 'Bibite' },
    pl: { label: 'Napoje' },
    uk: { label: 'Напої' },
    de: { label: 'Getränke' },
    fr: { label: 'Boissons' },
    no: { label: 'Drikke' },
  },
  items: [
    { id: 'red-bull',        slug: 'red-bull',        price: '200',
      i18n: {
        en: { name: 'Red Bull', desc: 'Energy drink.' },
        sq: { name: 'Red Bull', desc: 'Pije energjike.' },
        it: { name: 'Red Bull', desc: 'Bevanda energetica.' },
        pl: { name: 'Red Bull', desc: 'Napój energetyczny.' },
        uk: { name: 'Red Bull', desc: 'Енергетичний напій.' },
        de: { name: 'Red Bull', desc: 'Energydrink.' },
        fr: { name: 'Red Bull', desc: 'Boisson énergisante.' },
        no: { name: 'Red Bull', desc: 'Energidrikk.' },
      } },
    { id: 'glina-vitamina', slug: 'glina-vitamina', price: '100',
      variants: [{ label: 'Harmony', price: '100' }, { label: 'Immunity', price: '100' }],
      i18n: {
        en: { name: 'Glina Vitamina', desc: 'Vitamin water, apple and aloe vera or orange.' },
        sq: { name: 'Glina Vitamina', desc: 'Ujë vitaminash, mollë dhe aloe vera ose portokall.' },
        it: { name: 'Glina Vitamina', desc: 'Acqua vitaminica, mela e aloe vera oppure arancia.' },
        pl: { name: 'Glina Vitamina', desc: 'Woda witaminowa, jabłko i aloes lub pomarańcza.' },
        uk: { name: 'Glina Vitamina', desc: 'Вітамінна вода, яблуко й алое віра або апельсин.' },
        de: { name: 'Glina Vitamina', desc: 'Vitaminwasser, Apfel und Aloe Vera oder Orange.' },
        fr: { name: 'Glina Vitamina', desc: 'Eau vitaminée, pomme et aloe vera ou orange.' },
        no: { name: 'Glina Vitamina', desc: 'Vitaminvann, eple og aloe vera eller appelsin.' },
      } },
    { id: 'sparkling-water', slug: 'sparkling-water', price: '70',
      i18n: {
        en: { name: 'Sparkling Water', desc: 'Natural sparkling water.' },
        sq: { name: 'Sparkling Water', desc: 'Ujë natyral me gaz.' },
        it: { name: 'Sparkling Water', desc: 'Acqua naturale frizzante.' },
        pl: { name: 'Sparkling Water', desc: 'Naturalna woda gazowana.' },
        uk: { name: 'Sparkling Water', desc: 'Природна газована вода.' },
        de: { name: 'Sparkling Water', desc: 'Natürliches Wasser mit Kohlensäure.' },
        fr: { name: 'Sparkling Water', desc: 'Eau pétillante naturelle.' },
        no: { name: 'Sparkling Water', desc: 'Naturlig kullsyreholdig vann.' },
      } },
    { id: 'glina-still',     slug: 'glina-still',     price: '150',
      i18n: {
        en: { name: 'Glina Still Water', desc: 'Natural mineral water.' },
        sq: { name: 'Glina Still Water', desc: 'Ujë natyral mineral.' },
        it: { name: 'Glina Still Water', desc: 'Acqua minerale naturale.' },
        pl: { name: 'Glina Still Water', desc: 'Naturalna woda mineralna.' },
        uk: { name: 'Glina Still Water', desc: 'Природна мінеральна вода.' },
        de: { name: 'Glina Still Water', desc: 'Natürliches Mineralwasser.' },
        fr: { name: 'Glina Still Water', desc: 'Eau minérale naturelle.' },
        no: { name: 'Glina Still Water', desc: 'Naturlig mineralvann.' },
      } },
    { id: 'spring-still',    slug: 'spring-still',    price: '150',
      i18n: {
        en: { name: 'Spring Water', desc: 'Oligomineral still water.' },
        sq: { name: 'Spring Water', desc: 'Ujë oligomineral pa gaz.' },
        it: { name: 'Spring Water', desc: 'Acqua oligominerale naturale.' },
        pl: { name: 'Spring Water', desc: 'Woda oligomineralna niegazowana.' },
        uk: { name: 'Spring Water', desc: 'Оліго-мінеральна вода без газу.' },
        de: { name: 'Spring Water', desc: 'Oligomineralisches stilles Wasser.' },
        fr: { name: 'Spring Water', desc: 'Eau plate oligo-minérale.' },
        no: { name: 'Spring Water', desc: 'Oligomineralsk vann uten kullsyre.' },
      } },
    { id: 'bravo', slug: 'bravo', price: '150',
      variants: [{ label: 'Peach', price: '150' }, { label: 'Red Grape', price: '150' }, { label: 'Green Apple', price: '150' }],
      i18n: {
        en: { name: 'Bravo', desc: 'Fruit juice.' },
        sq: { name: 'Bravo', desc: 'Lëng frutash.' },
        it: { name: 'Bravo', desc: 'Succo di frutta.' },
        pl: { name: 'Bravo', desc: 'Sok owocowy.' },
        uk: { name: 'Bravo', desc: 'Фруктовий сік.' },
        de: { name: 'Bravo', desc: 'Fruchtsaft.' },
        fr: { name: 'Bravo', desc: 'Jus de fruits.' },
        no: { name: 'Bravo', desc: 'Fruktjuice.' },
      } },
    { id: 'fanta', slug: 'fanta', price: '150',
      variants: [{ label: 'Orange', price: '150' }, { label: 'Exotic', price: '150' }],
      i18n: {
        en: { name: 'Fanta', desc: 'Fruit soda.' },
        sq: { name: 'Fanta', desc: 'Pije freskuese me fruta.' },
        it: { name: 'Fanta', desc: 'Bibita gassata alla frutta.' },
        pl: { name: 'Fanta', desc: 'Napój gazowany owocowy.' },
        uk: { name: 'Fanta', desc: 'Фруктова газованка.' },
        de: { name: 'Fanta', desc: 'Fruchtlimonade.' },
        fr: { name: 'Fanta', desc: 'Soda aux fruits.' },
        no: { name: 'Fanta', desc: 'Fruktbrus.' },
      } },
    { id: 'pepsi',           slug: 'pepsi',           price: '150',
      i18n: {
        en: { name: 'Pepsi', desc: 'Cola.' },
        sq: { name: 'Pepsi', desc: 'Kola.' },
        it: { name: 'Pepsi', desc: 'Cola.' },
        pl: { name: 'Pepsi', desc: 'Cola.' },
        uk: { name: 'Pepsi', desc: 'Кола.' },
        de: { name: 'Pepsi', desc: 'Cola.' },
        fr: { name: 'Pepsi', desc: 'Cola.' },
        no: { name: 'Pepsi', desc: 'Cola.' },
      } },
    { id: 'lemon-soda',      slug: 'lemon-soda',      price: '150',
      i18n: {
        en: { name: 'Lemon Soda', desc: 'Italian lemon soda (Crodo).' },
        sq: { name: 'Lemon Soda', desc: 'Pije limoni italiane (Crodo).' },
        it: { name: 'Lemon Soda', desc: 'Soda al limone italiana (Crodo).' },
        pl: { name: 'Lemon Soda', desc: 'Włoska lemoniada gazowana (Crodo).' },
        uk: { name: 'Lemon Soda', desc: 'Італійська лимонна газованка (Crodo).' },
        de: { name: 'Lemon Soda', desc: 'Italienische Zitronenlimonade (Crodo).' },
        fr: { name: 'Lemon Soda', desc: 'Soda italien au citron (Crodo).' },
        no: { name: 'Lemon Soda', desc: 'Italiensk sitronbrus (Crodo).' },
      } },
    { id: 'ivi', slug: 'ivi', price: '150',
      variants: [{ label: 'Limon', price: '150' }, { label: 'Ricoco', price: '150' }],
      i18n: {
        en: { name: 'ivi', desc: 'Sparkling soda.' },
        sq: { name: 'ivi', desc: 'Pije freskuese me gaz.' },
        it: { name: 'ivi', desc: 'Bibita gassata.' },
        pl: { name: 'ivi', desc: 'Napój gazowany.' },
        uk: { name: 'ivi', desc: 'Газований напій.' },
        de: { name: 'ivi', desc: 'Sprudel-Limonade.' },
        fr: { name: 'ivi', desc: 'Soda pétillant.' },
        no: { name: 'ivi', desc: 'Kullsyreholdig brus.' },
      } },
    { id: 'coccodrillo-bitter', slug: 'coccodrillo-bitter', price: '150',
      i18n: {
        en: { name: 'Coccodrillo Bitter', desc: 'Non-alcoholic bitter aperitif.' },
        sq: { name: 'Coccodrillo Bitter', desc: 'Aperitiv i hidhur pa alkool.' },
        it: { name: 'Coccodrillo Bitter', desc: 'Aperitivo amaro analcolico.' },
        pl: { name: 'Coccodrillo Bitter', desc: 'Bezalkoholowy gorzki aperitif.' },
        uk: { name: 'Coccodrillo Bitter', desc: 'Безалкогольний гіркий аперитив.' },
        de: { name: 'Coccodrillo Bitter', desc: 'Alkoholfreier bitterer Aperitif.' },
        fr: { name: 'Coccodrillo Bitter', desc: 'Apéritif amer sans alcool.' },
        no: { name: 'Coccodrillo Bitter', desc: 'Alkoholfri bitter aperitiff.' },
      } },
    { id: 'lipton', slug: 'lipton', price: '150',
      variants: [{ label: 'Lemon', price: '150' }, { label: 'Peach', price: '150' }],
      i18n: {
        en: { name: 'Lipton Ice Tea', desc: 'Chilled iced tea.' },
        sq: { name: 'Lipton Ice Tea', desc: 'Çaj i ftohtë i akullt.' },
        it: { name: 'Lipton Ice Tea', desc: 'Tè freddo ghiacciato.' },
        pl: { name: 'Lipton Ice Tea', desc: 'Schłodzona mrożona herbata.' },
        uk: { name: 'Lipton Ice Tea', desc: 'Охолоджений холодний чай.' },
        de: { name: 'Lipton Ice Tea', desc: 'Gekühlter Eistee.' },
        fr: { name: 'Lipton Ice Tea', desc: 'Thé glacé frais.' },
        no: { name: 'Lipton Ice Tea', desc: 'Kald iste.' },
      } },
    { id: 'energy-852',      slug: 'energy-852',      price: '150',
      i18n: {
        en: { name: 'B52', desc: 'Energy drink.' },
        sq: { name: 'B52', desc: 'Pije energjike.' },
        it: { name: 'B52', desc: 'Bevanda energetica.' },
        pl: { name: 'B52', desc: 'Napój energetyczny.' },
        uk: { name: 'B52', desc: 'Енергетичний напій.' },
        de: { name: 'B52', desc: 'Energydrink.' },
        fr: { name: 'B52', desc: 'Boisson énergisante.' },
        no: { name: 'B52', desc: 'Energidrikk.' },
      } },
    { id: 'anna-iced-coffee', slug: 'anna-iced-coffee', price: '150',
      i18n: {
        en: { name: 'Iced Coffee', desc: 'Cold coffee drink with milk, cappuccino.' },
        sq: { name: 'Iced Coffee', desc: 'Pije kafeje e ftohtë me qumësht, kapuçino.' },
        it: { name: 'Iced Coffee', desc: 'Bevanda al caffè fredda con latte, cappuccino.' },
        pl: { name: 'Iced Coffee', desc: 'Zimny napój kawowy z mlekiem, cappuccino.' },
        uk: { name: 'Iced Coffee', desc: 'Холодний кавовий напій з молоком, капучино.' },
        de: { name: 'Iced Coffee', desc: 'Kaltes Kaffeegetränk mit Milch, Cappuccino.' },
        fr: { name: 'Iced Coffee', desc: 'Boisson au café froide avec lait, cappuccino.' },
        no: { name: 'Iced Coffee', desc: 'Kald kaffedrikk med melk, cappuccino.' },
      } },
    { id: 'lufra-dhalle',    slug: 'lufra-dhalle',    price: '150',
      i18n: {
        en: { name: 'Lufra Dhallë', desc: 'Traditional salted yogurt drink (ayran).' },
        sq: { name: 'Lufra Dhallë', desc: 'Dhallë tradicionale (ajran).' },
        it: { name: 'Lufra Dhallë', desc: 'Bevanda tradizionale di yogurt salato (ayran).' },
        pl: { name: 'Lufra Dhallë', desc: 'Tradycyjny słony napój jogurtowy (ayran).' },
        uk: { name: 'Lufra Dhallë', desc: 'Традиційний солоний йогуртовий напій (айран).' },
        de: { name: 'Lufra Dhallë', desc: 'Traditionelles gesalzenes Joghurtgetränk (Ayran).' },
        fr: { name: 'Lufra Dhallë', desc: 'Boisson traditionnelle au yaourt salé (ayran).' },
        no: { name: 'Lufra Dhallë', desc: 'Tradisjonell saltet yoghurtdrikk (ayran).' },
      } },
  ],
}

// ── FOOD ── (foodSections → right category tab) ─────────────────────────────

const desserts: MenuSection = {
  key: 'pastries',
  type: 'food',
  i18n: {
    en: { label: 'Desserts',  note: "If you haven't finished your dessert, we'll gladly pack it to go. Enjoy!" },
    sq: { label: 'Ëmbëlsira', note: 'Nëse nuk e mbaroni ëmbëlsirën, me kënaqësi jua paketojmë për ta marrë me vete. Shijoni!' },
    it: { label: 'Dolci',     note: 'Se non finisci il dolce, te lo incartiamo volentieri da portare via. Buon appetito!' },
    pl: { label: 'Desery',    note: 'Jeśli nie dokończysz deseru, chętnie zapakujemy go na wynos. Smacznego!' },
    uk: { label: 'Десерти',   note: 'Якщо не доїли десерт, залюбки спакуємо з собою. Смачного!' },
    de: { label: 'Desserts',  note: 'Wenn du dein Dessert nicht schaffst, packen wir es dir gerne zum Mitnehmen ein. Guten Appetit!' },
    fr: { label: 'Desserts',  note: "Si vous ne finissez pas votre dessert, nous vous l'emballons volontiers à emporter. Bon appétit !" },
    no: { label: 'Desserter', note: 'Hvis du ikke blir ferdig med desserten, pakker vi den gjerne til deg. Vel bekomme!' },
  },
  items: [
    // Order = menu-engineering: hook first, top-price champion in slot 2,
    // premiums high, cheap buried, a premium closes the last sweet spot.
    { id: 'trilece',     slug: 'trilece',     price: '150', posterSrc: '/venue-assets/amour/trilece.jpg',
      i18n: {
        en: { name: 'Trileçe', desc: 'Very sweet. Milk, heavy cream, caramel cake.' },
        sq: { name: 'Trileçe', desc: 'Shumë e ëmbël. Qumësht, ajkë e trashë, tortë karameli.' },
        it: { name: 'Trileçe', desc: 'Molto dolce. Latte, panna, torta al caramello.' },
        pl: { name: 'Trileçe', desc: 'Bardzo słodkie. Mleko, śmietana, ciasto karmelowe.' },
        uk: { name: 'Trileçe', desc: 'Дуже солодкий. Молоко, вершки, карамельний корж.' },
        de: { name: 'Trileçe', desc: 'Sehr süß. Milch, Sahne, Karamellkuchen.' },
        fr: { name: 'Trileçe', desc: 'Très sucré. Lait, crème épaisse, gâteau au caramel.' },
        no: { name: 'Trileçe', desc: 'Veldig søt. Melk, kremfløte, karamellkake.' },
      } },
    { id: 'cheesecake',  slug: 'cheesecake',  price: '350', posterSrc: '/venue-assets/amour/cheesecake.jpg', videoSrc: '/venue-assets/amour/cheesecake.mp4',
      i18n: {
        en: { name: 'Cheesecake', desc: 'Medium sweet. Forest berries.' },
        sq: { name: 'Cheesecake', desc: 'Mesatarisht e ëmbël. Manaferra pylli.' },
        it: { name: 'Cheesecake', desc: 'Mediamente dolce. Frutti di bosco.' },
        pl: { name: 'Cheesecake', desc: 'Średnio słodkie. Owoce leśne.' },
        uk: { name: 'Cheesecake', desc: 'Помірно солодкий. Лісові ягоди.' },
        de: { name: 'Cheesecake', desc: 'Mittelsüß. Waldbeeren.' },
        fr: { name: 'Cheesecake', desc: 'Moyennement sucré. Fruits des bois.' },
        no: { name: 'Cheesecake', desc: 'Middels søt. Skogsbær.' },
      } },
    { id: 'pastasciutta', slug: 'pastasciutta', price: '100', posterSrc: '/venue-assets/amour/pasta-choc.jpg',
      variants: [
        { label: 'Chocolate', price: '150', posterSrc: '/venue-assets/amour/pasta-choc.jpg' },
        { label: 'Caramel',   price: '100', posterSrc: '/venue-assets/amour/pasta-caramel.jpg' },
        { label: 'Pistachio', price: '150', posterSrc: '/venue-assets/amour/pasta-pistachio.jpg' },
      ],
      i18n: {
        en: { name: 'Pastasciutta', desc: 'Medium sweet. Choux pastry with vanilla cream.' },
        sq: { name: 'Pastasciutta', desc: 'Mesatarisht e ëmbël. Brumë çu me krem vanilje.' },
        it: { name: 'Pastasciutta', desc: 'Mediamente dolce. Pasta choux con crema alla vaniglia.' },
        pl: { name: 'Pastasciutta', desc: 'Średnio słodkie. Ciasto parzone z kremem waniliowym.' },
        uk: { name: 'Pastasciutta', desc: 'Помірно солодкий. Заварне тісто з ванільним кремом.' },
        de: { name: 'Pastasciutta', desc: 'Mittelsüß. Brandteig mit Vanillecreme.' },
        fr: { name: 'Pastasciutta', desc: 'Moyennement sucré. Pâte à choux avec crème vanille.' },
        no: { name: 'Pastasciutta', desc: 'Middels søt. Vannbakkels med vaniljekrem.' },
      } },
    { id: 'strawberry-d', slug: 'strawberry-d', price: '300', posterSrc: '/venue-assets/amour/strawberry-d.jpg',
      i18n: {
        en: { name: 'Strawberry', desc: 'Medium sweet. Vanilla cream with strawberry pieces inside.' },
        sq: { name: 'Strawberry', desc: 'Mesatarisht e ëmbël. Krem vanilje me copa luleshtrydhe brenda.' },
        it: { name: 'Strawberry', desc: "Mediamente dolce. Crema alla vaniglia con pezzi di fragola all'interno." },
        pl: { name: 'Strawberry', desc: 'Średnio słodkie. Krem waniliowy z kawałkami truskawek w środku.' },
        uk: { name: 'Strawberry', desc: 'Помірно солодкий. Ванільний крем зі шматочками полуниці всередині.' },
        de: { name: 'Strawberry', desc: 'Mittelsüß. Vanillecreme mit Erdbeerstücken.' },
        fr: { name: 'Strawberry', desc: "Moyennement sucré. Crème vanille avec des morceaux de fraise à l'intérieur." },
        no: { name: 'Strawberry', desc: 'Middels søt. Vaniljekrem med jordbærbiter inni.' },
      } },
    { id: 'millefeuille', slug: 'millefeuille', price: '150', posterSrc: '/venue-assets/amour/millefeuille.jpg', badge: 'Best seller', house: true,
      i18n: {
        en: { name: 'Millefeuille', desc: 'Medium sweet. Puff pastry, vanilla cream.' },
        sq: { name: 'Millefeuille', desc: 'Mesatarisht e ëmbël. Brumë me shtresa, krem vanilje.' },
        it: { name: 'Millefeuille', desc: 'Mediamente dolce. Pasta sfoglia, crema alla vaniglia.' },
        pl: { name: 'Millefeuille', desc: 'Średnio słodkie. Ciasto francuskie, krem waniliowy.' },
        uk: { name: 'Millefeuille', desc: 'Помірно солодкий. Листкове тісто, ванільний крем.' },
        de: { name: 'Millefeuille', desc: 'Mittelsüß. Blätterteig, Vanillecreme.' },
        fr: { name: 'Millefeuille', desc: 'Moyennement sucré. Pâte feuilletée, crème vanille.' },
        no: { name: 'Millefeuille', desc: 'Middels søt. Butterdeig, vaniljekrem.' },
      } },
    { id: 'apple',       slug: 'apple',       price: '300', ph: 'fruit',
      i18n: {
        en: { name: 'Apple', desc: 'Medium sweet. Vanilla cream with apple pieces inside.' },
        sq: { name: 'Apple', desc: 'Mesatarisht e ëmbël. Krem vanilje me copa molle brenda.' },
        it: { name: 'Apple', desc: "Mediamente dolce. Crema alla vaniglia con pezzi di mela all'interno." },
        pl: { name: 'Apple', desc: 'Średnio słodkie. Krem waniliowy z kawałkami jabłka w środku.' },
        uk: { name: 'Apple', desc: 'Помірно солодкий. Ванільний крем зі шматочками яблука всередині.' },
        de: { name: 'Apple', desc: 'Mittelsüß. Vanillecreme mit Apfelstücken.' },
        fr: { name: 'Apple', desc: "Moyennement sucré. Crème vanille avec des morceaux de pomme à l'intérieur." },
        no: { name: 'Apple', desc: 'Middels søt. Vaniljekrem med eplebiter inni.' },
      } },
    { id: 'mango',       slug: 'mango',       price: '300', ph: 'fruit',
      i18n: {
        en: { name: 'Mango', desc: 'Medium sweet. Vanilla cream with mango pieces inside.' },
        sq: { name: 'Mango', desc: 'Mesatarisht e ëmbël. Krem vanilje me copa mango brenda.' },
        it: { name: 'Mango', desc: "Mediamente dolce. Crema alla vaniglia con pezzi di mango all'interno." },
        pl: { name: 'Mango', desc: 'Średnio słodkie. Krem waniliowy z kawałkami mango w środku.' },
        uk: { name: 'Mango', desc: 'Помірно солодкий. Ванільний крем зі шматочками манго всередині.' },
        de: { name: 'Mango', desc: 'Mittelsüß. Vanillecreme mit Mangostücken.' },
        fr: { name: 'Mango', desc: "Moyennement sucré. Crème vanille avec des morceaux de mangue à l'intérieur." },
        no: { name: 'Mango', desc: 'Middels søt. Vaniljekrem med mangobiter inni.' },
      } },
    { id: 'lotus',       slug: 'lotus',       price: '250', posterSrc: '/venue-assets/amour/lotus.jpg',
      i18n: {
        en: { name: 'Lotus', desc: 'Medium sweet. Vanilla cream, chocolate, biscuit.' },
        sq: { name: 'Lotus', desc: 'Mesatarisht e ëmbël. Krem vanilje, çokollatë, biskotë.' },
        it: { name: 'Lotus', desc: 'Mediamente dolce. Crema alla vaniglia, cioccolato, biscotto.' },
        pl: { name: 'Lotus', desc: 'Średnio słodkie. Krem waniliowy, czekolada, herbatnik.' },
        uk: { name: 'Lotus', desc: 'Помірно солодкий. Ванільний крем, шоколад, печиво.' },
        de: { name: 'Lotus', desc: 'Mittelsüß. Vanillecreme, Schokolade, Keks.' },
        fr: { name: 'Lotus', desc: 'Moyennement sucré. Crème vanille, chocolat, biscuit.' },
        no: { name: 'Lotus', desc: 'Middels søt. Vaniljekrem, sjokolade, kjeks.' },
      } },
    { id: 'tiramisu',    slug: 'tiramisu',    price: '200', posterSrc: '/venue-assets/amour/tiramisu.jpg',
      i18n: {
        en: { name: 'Tiramisu Cacao', desc: 'Medium sweet. Biscuit, mascarpone, cacao.' },
        sq: { name: 'Tiramisu Cacao', desc: 'Mesatarisht e ëmbël. Biskotë, maskarpone, kakao.' },
        it: { name: 'Tiramisu Cacao', desc: 'Mediamente dolce. Savoiardi, mascarpone, cacao.' },
        pl: { name: 'Tiramisu Cacao', desc: 'Średnio słodkie. Biszkopt, mascarpone, kakao.' },
        uk: { name: 'Tiramisu Cacao', desc: 'Помірно солодкий. Печиво, маскарпоне, какао.' },
        de: { name: 'Tiramisu Cacao', desc: 'Mittelsüß. Löffelbiskuit, Mascarpone, Kakao.' },
        fr: { name: 'Tiramisu Cacao', desc: 'Moyennement sucré. Biscuit, mascarpone, cacao.' },
        no: { name: 'Tiramisu Cacao', desc: 'Middels søt. Kjeks, mascarpone, kakao.' },
      } },
    { id: 'sacher',      slug: 'sacher',      price: '200', posterSrc: '/venue-assets/amour/sacher.jpg',
      i18n: {
        en: { name: 'Sacher', desc: 'Medium sweet. Apricot jam, chocolate.' },
        sq: { name: 'Sacher', desc: 'Mesatarisht e ëmbël. Reçel kajsie, çokollatë.' },
        it: { name: 'Sacher', desc: 'Mediamente dolce. Confettura di albicocche, cioccolato.' },
        pl: { name: 'Sacher', desc: 'Średnio słodkie. Dżem morelowy, czekolada.' },
        uk: { name: 'Sacher', desc: 'Помірно солодкий. Абрикосовий джем, шоколад.' },
        de: { name: 'Sacher', desc: 'Mittelsüß. Aprikosenmarmelade, Schokolade.' },
        fr: { name: 'Sacher', desc: "Moyennement sucré. Confiture d'abricot, chocolat." },
        no: { name: 'Sacher', desc: 'Middels søt. Aprikossyltetøy, sjokolade.' },
      } },
    { id: 'ferrero',     slug: 'ferrero',     price: '200', ph: 'cake-slice',
      i18n: {
        en: { name: 'Ferrero', desc: 'Very sweet. Nuts, chocolate, vanilla cream.' },
        sq: { name: 'Ferrero', desc: 'Shumë e ëmbël. Arra, çokollatë, krem vanilje.' },
        it: { name: 'Ferrero', desc: 'Molto dolce. Nocciole, cioccolato, crema alla vaniglia.' },
        pl: { name: 'Ferrero', desc: 'Bardzo słodkie. Orzechy, czekolada, krem waniliowy.' },
        uk: { name: 'Ferrero', desc: 'Дуже солодкий. Горіхи, шоколад, ванільний крем.' },
        de: { name: 'Ferrero', desc: 'Sehr süß. Nüsse, Schokolade, Vanillecreme.' },
        fr: { name: 'Ferrero', desc: 'Très sucré. Noisettes, chocolat, crème vanille.' },
        no: { name: 'Ferrero', desc: 'Veldig søt. Nøtter, sjokolade, vaniljekrem.' },
      } },
    { id: 'raffaello',   slug: 'raffaello',   price: '200', posterSrc: '/venue-assets/amour/raffaello.jpg',
      i18n: {
        en: { name: 'Raffaello', desc: 'Medium sweet. Sponge cake, vanilla cream, Raffaello.' },
        sq: { name: 'Raffaello', desc: 'Mesatarisht e ëmbël. Pandispanjë, krem vanilje, Raffaello.' },
        it: { name: 'Raffaello', desc: 'Mediamente dolce. Pan di Spagna, crema alla vaniglia, Raffaello.' },
        pl: { name: 'Raffaello', desc: 'Średnio słodkie. Biszkopt, krem waniliowy, Raffaello.' },
        uk: { name: 'Raffaello', desc: 'Помірно солодкий. Бісквіт, ванільний крем, Raffaello.' },
        de: { name: 'Raffaello', desc: 'Mittelsüß. Biskuit, Vanillecreme, Raffaello.' },
        fr: { name: 'Raffaello', desc: 'Moyennement sucré. Génoise, crème vanille, Raffaello.' },
        no: { name: 'Raffaello', desc: 'Middels søt. Sukkerbrød, vaniljekrem, Raffaello.' },
      } },
    { id: 'red-velvet',  slug: 'red-velvet',  price: '200', ph: 'cake-slice',
      i18n: {
        en: { name: 'Red Velvet', desc: 'Medium sweet. Red sponge cake, cherry cream.' },
        sq: { name: 'Red Velvet', desc: 'Mesatarisht e ëmbël. Pandispanjë e kuqe, krem qershie.' },
        it: { name: 'Red Velvet', desc: 'Mediamente dolce. Pan di Spagna rosso, crema di ciliegia.' },
        pl: { name: 'Red Velvet', desc: 'Średnio słodkie. Czerwony biszkopt, krem wiśniowy.' },
        uk: { name: 'Red Velvet', desc: 'Помірно солодкий. Червоний бісквіт, вишневий крем.' },
        de: { name: 'Red Velvet', desc: 'Mittelsüß. Roter Biskuit, Kirschcreme.' },
        fr: { name: 'Red Velvet', desc: 'Moyennement sucré. Génoise rouge, crème de cerise.' },
        no: { name: 'Red Velvet', desc: 'Middels søt. Rødt sukkerbrød, kirsebærkrem.' },
      } },
    { id: 'mousse',      slug: 'mousse',      price: '200', ph: 'cake-slice',
      i18n: {
        en: { name: 'Mousse', desc: 'Medium sweet. Chocolate, vanilla cream.' },
        sq: { name: 'Mousse', desc: 'Mesatarisht e ëmbël. Çokollatë, krem vanilje.' },
        it: { name: 'Mousse', desc: 'Mediamente dolce. Cioccolato, crema alla vaniglia.' },
        pl: { name: 'Mousse', desc: 'Średnio słodkie. Czekolada, krem waniliowy.' },
        uk: { name: 'Mousse', desc: 'Помірно солодкий. Шоколад, ванільний крем.' },
        de: { name: 'Mousse', desc: 'Mittelsüß. Schokolade, Vanillecreme.' },
        fr: { name: 'Mousse', desc: 'Moyennement sucré. Chocolat, crème vanille.' },
        no: { name: 'Mousse', desc: 'Middels søt. Sjokolade, vaniljekrem.' },
      } },
    { id: 'snickers',    slug: 'snickers',    price: '200', posterSrc: '/venue-assets/amour/snickers.jpg',
      i18n: {
        en: { name: 'Snickers', desc: 'Very sweet. Snickers and chocolate flavour.' },
        sq: { name: 'Snickers', desc: 'Shumë e ëmbël. Shije Snickers dhe çokollate.' },
        it: { name: 'Snickers', desc: 'Molto dolce. Gusto Snickers e cioccolato.' },
        pl: { name: 'Snickers', desc: 'Bardzo słodkie. Smak Snickers i czekolady.' },
        uk: { name: 'Snickers', desc: 'Дуже солодкий. Смак Snickers і шоколаду.' },
        de: { name: 'Snickers', desc: 'Sehr süß. Snickers- und Schokoladengeschmack.' },
        fr: { name: 'Snickers', desc: 'Très sucré. Saveur Snickers et chocolat.' },
        no: { name: 'Snickers', desc: 'Veldig søt. Snickers- og sjokoladesmak.' },
      } },
    { id: 'panna-cotta', slug: 'panna-cotta', price: '200', posterSrc: '/venue-assets/amour/panna-cotta.jpg',
      i18n: {
        en: { name: 'Panna Cotta', desc: 'Lightly sweet. Milk and forest fruit.' },
        sq: { name: 'Panna Cotta', desc: 'Paksa e ëmbël. Qumësht dhe fruta pylli.' },
        it: { name: 'Panna Cotta', desc: 'Poco dolce. Latte e frutti di bosco.' },
        pl: { name: 'Panna Cotta', desc: 'Lekko słodkie. Mleko i owoce leśne.' },
        uk: { name: 'Panna Cotta', desc: 'Злегка солодкий. Молоко й лісові ягоди.' },
        de: { name: 'Panna Cotta', desc: 'Leicht süß. Milch und Waldfrüchte.' },
        fr: { name: 'Panna Cotta', desc: 'Peu sucré. Lait et fruits des bois.' },
        no: { name: 'Panna Cotta', desc: 'Lett søt. Melk og skogsbær.' },
      } },
    { id: 'forest-fruits', slug: 'forest-fruits', price: '180', ph: 'dessert',
      i18n: {
        en: { name: 'Forest Fruits', desc: 'Medium sweet. Sponge cake and vanilla cream with forest-fruit pieces inside.' },
        sq: { name: 'Forest Fruits', desc: 'Mesatarisht e ëmbël. Pandispanjë dhe krem vanilje me copa frutash pylli brenda.' },
        it: { name: 'Forest Fruits', desc: "Mediamente dolce. Pan di Spagna e crema alla vaniglia con pezzi di frutti di bosco all'interno." },
        pl: { name: 'Forest Fruits', desc: 'Średnio słodkie. Biszkopt i krem waniliowy z kawałkami owoców leśnych w środku.' },
        uk: { name: 'Forest Fruits', desc: 'Помірно солодкий. Бісквіт і ванільний крем зі шматочками лісових ягід всередині.' },
        de: { name: 'Forest Fruits', desc: 'Mittelsüß. Biskuit und Vanillecreme mit Waldfruchtstücken.' },
        fr: { name: 'Forest Fruits', desc: "Moyennement sucré. Génoise et crème vanille avec des morceaux de fruits des bois à l'intérieur." },
        no: { name: 'Forest Fruits', desc: 'Middels søt. Sukkerbrød og vaniljekrem med skogsbærbiter inni.' },
      } },
    { id: 'raffaello-paste', slug: 'raffaello-paste', price: '200', ph: 'dessert',
      i18n: {
        en: { name: 'Raffaello Paste', desc: 'Medium sweet. Sponge cake, vanilla cream, Raffaello.' },
        sq: { name: 'Raffaello Paste', desc: 'Mesatarisht e ëmbël. Pandispanjë, krem vanilje, Raffaello.' },
        it: { name: 'Raffaello Paste', desc: 'Mediamente dolce. Pan di Spagna, crema alla vaniglia, Raffaello.' },
        pl: { name: 'Raffaello Paste', desc: 'Średnio słodkie. Biszkopt, krem waniliowy, Raffaello.' },
        uk: { name: 'Raffaello Paste', desc: 'Помірно солодкий. Бісквіт, ванільний крем, Raffaello.' },
        de: { name: 'Raffaello Paste', desc: 'Mittelsüß. Biskuit, Vanillecreme, Raffaello.' },
        fr: { name: 'Raffaello Paste', desc: 'Moyennement sucré. Génoise, crème vanille, Raffaello.' },
        no: { name: 'Raffaello Paste', desc: 'Middels søt. Sukkerbrød, vaniljekrem, Raffaello.' },
      } },
    { id: 'pistachio',   slug: 'pistachio',   price: '300', posterSrc: '/venue-assets/amour/pistachio.jpg',
      i18n: {
        en: { name: 'Pistachio', desc: 'Medium sweet. Pistachio, vanilla cream.' },
        sq: { name: 'Pistachio', desc: 'Mesatarisht e ëmbël. Fëstëk, krem vanilje.' },
        it: { name: 'Pistachio', desc: 'Mediamente dolce. Pistacchio, crema alla vaniglia.' },
        pl: { name: 'Pistachio', desc: 'Średnio słodkie. Pistacja, krem waniliowy.' },
        uk: { name: 'Pistachio', desc: 'Помірно солодкий. Фісташка, ванільний крем.' },
        de: { name: 'Pistachio', desc: 'Mittelsüß. Pistazie, Vanillecreme.' },
        fr: { name: 'Pistachio', desc: 'Moyennement sucré. Pistache, crème vanille.' },
        no: { name: 'Pistachio', desc: 'Middels søt. Pistasj, vaniljekrem.' },
      } },
  ],
}

const cakes: MenuSection = {
  key: 'cakes',
  type: 'food',
  i18n: {
    en: { label: 'Cakes',  note: 'Our cakes come in two sizes, M and L. Sizes vary from cake to cake, so ask us about each one.' },
    sq: { label: 'Torte',  note: 'Tortat tona vijnë në dy madhësi, M dhe L. Madhësitë ndryshojnë nga torta në tortë, prandaj na pyesni për secilën.' },
    it: { label: 'Torte',  note: 'Le nostre torte sono in due misure, M e L. Le misure variano da torta a torta, quindi chiedeteci per ciascuna.' },
    pl: { label: 'Ciasta', note: 'Nasze ciasta są w dwóch rozmiarach, M i L. Rozmiary różnią się między ciastami, więc pytajcie o każde.' },
    uk: { label: 'Торти',  note: 'Наші торти у двох розмірах, M і L. Розміри різняться від торта до торта, тож питайте про кожен.' },
    de: { label: 'Kuchen', note: 'Unsere Kuchen gibt es in zwei Größen, M und L. Die Größen variieren je nach Kuchen, fragen Sie uns nach jedem.' },
    fr: { label: 'Gâteaux', note: "Nos gâteaux existent en deux tailles, M et L. Les tailles varient d'un gâteau à l'autre, demandez-nous pour chacun." },
    no: { label: 'Kaker',  note: 'Kakene våre finnes i to størrelser, M og L. Størrelsene varierer fra kake til kake, så spør oss om hver enkelt.' },
  },
  items: [
    { id: 'cake-me-peta',    slug: 'cake-me-peta',    price: '1000', posterSrc: '/venue-assets/amour/cake-me-peta.jpg',
      sizes: [{ label: 'M', price: '1000' }, { label: 'L', price: '1200' }],
      i18n: {
        en: { name: 'Me Peta', desc: 'Medium sweet. Layers, vanilla cream, sponge cake, forest fruits.' },
        sq: { name: 'Me Peta', desc: 'Mesatarisht e ëmbël. Shtresa, krem vanilje, pandispanjë, fruta pylli.' },
        it: { name: 'Me Peta', desc: 'Mediamente dolce. Strati, crema alla vaniglia, pan di Spagna, frutti di bosco.' },
        pl: { name: 'Me Peta', desc: 'Średnio słodkie. Warstwy, krem waniliowy, biszkopt, owoce leśne.' },
        uk: { name: 'Me Peta', desc: 'Помірно солодкий. Шари, ванільний крем, бісквіт, лісові ягоди.' },
        de: { name: 'Me Peta', desc: 'Mittelsüß. Schichten, Vanillecreme, Biskuit, Waldfrüchte.' },
        fr: { name: 'Me Peta', desc: 'Moyennement sucré. Couches, crème vanille, génoise, fruits des bois.' },
        no: { name: 'Me Peta', desc: 'Middels søt. Lag, vaniljekrem, sukkerbrød, skogsbær.' },
      } },
    { id: 'cake-chocolate',  slug: 'cake-chocolate',  price: '1200', posterSrc: '/venue-assets/amour/cake-chocolate.jpg',
      sizes: [{ label: 'M', price: '1200' }, { label: 'L', price: '1500' }],
      i18n: {
        en: { name: 'Chocolate', desc: 'Medium sweet. Sponge cake, chocolate cream filling, chocolate coating.' },
        sq: { name: 'Chocolate', desc: 'Mesatarisht e ëmbël. Pandispanjë, mbushje me krem çokollate, glazurë çokollate.' },
        it: { name: 'Chocolate', desc: 'Mediamente dolce. Pan di Spagna, ripieno di crema al cioccolato, copertura di cioccolato.' },
        pl: { name: 'Chocolate', desc: 'Średnio słodkie. Biszkopt, nadzienie z kremu czekoladowego, polewa czekoladowa.' },
        uk: { name: 'Chocolate', desc: 'Помірно солодкий. Бісквіт, начинка з шоколадного крему, шоколадна глазур.' },
        de: { name: 'Chocolate', desc: 'Mittelsüß. Biskuit, Schokocremefüllung, Schokoladenüberzug.' },
        fr: { name: 'Chocolate', desc: 'Moyennement sucré. Génoise, garniture crème chocolat, enrobage chocolat.' },
        no: { name: 'Chocolate', desc: 'Middels søt. Sukkerbrød, sjokoladekremfyll, sjokoladetrekk.' },
      } },
    { id: 'cake-caramel',    slug: 'cake-caramel',    price: '1000', posterSrc: '/venue-assets/amour/cake-caramel.jpg',
      sizes: [{ label: 'M', price: '1000' }, { label: 'L', price: '1200' }],
      i18n: {
        en: { name: 'Caramel', desc: 'Very sweet. Sponge cake, caramel cream, vanilla cream.' },
        sq: { name: 'Caramel', desc: 'Shumë e ëmbël. Pandispanjë, krem karameli, krem vanilje.' },
        it: { name: 'Caramel', desc: 'Molto dolce. Pan di Spagna, crema al caramello, crema alla vaniglia.' },
        pl: { name: 'Caramel', desc: 'Bardzo słodkie. Biszkopt, krem karmelowy, krem waniliowy.' },
        uk: { name: 'Caramel', desc: 'Дуже солодкий. Бісквіт, карамельний крем, ванільний крем.' },
        de: { name: 'Caramel', desc: 'Sehr süß. Biskuit, Karamellcreme, Vanillecreme.' },
        fr: { name: 'Caramel', desc: 'Très sucré. Génoise, crème caramel, crème vanille.' },
        no: { name: 'Caramel', desc: 'Veldig søt. Sukkerbrød, karamellkrem, vaniljekrem.' },
      } },
    { id: 'cake-berries',    slug: 'cake-berries',    price: '1000', posterSrc: '/venue-assets/amour/cake-berries.jpg',
      sizes: [{ label: 'M', price: '1000' }, { label: 'L', price: '1200' }],
      i18n: {
        en: { name: 'Berries', desc: 'Medium sweet. Sponge cake, vanilla cream, forest-fruit flavour, berries on top, slightly tart.' },
        sq: { name: 'Berries', desc: 'Mesatarisht e ëmbël. Pandispanjë, krem vanilje, shije frutash pylli, manaferra sipër, paksa e thartë.' },
        it: { name: 'Berries', desc: 'Mediamente dolce. Pan di Spagna, crema alla vaniglia, gusto frutti di bosco, frutti di bosco sopra, leggermente aspro.' },
        pl: { name: 'Berries', desc: 'Średnio słodkie. Biszkopt, krem waniliowy, smak owoców leśnych, owoce na wierzchu, lekko kwaśne.' },
        uk: { name: 'Berries', desc: 'Помірно солодкий. Бісквіт, ванільний крем, смак лісових ягід, ягоди зверху, злегка кислуватий.' },
        de: { name: 'Berries', desc: 'Mittelsüß. Biskuit, Vanillecreme, Waldfruchtgeschmack, Beeren obenauf, leicht säuerlich.' },
        fr: { name: 'Berries', desc: 'Moyennement sucré. Génoise, crème vanille, saveur fruits des bois, fruits rouges dessus, légèrement acidulé.' },
        no: { name: 'Berries', desc: 'Middels søt. Sukkerbrød, vaniljekrem, skogsbærsmak, bær på toppen, litt syrlig.' },
      } },
    { id: 'cake-strawberry', slug: 'cake-strawberry', price: '1000', posterSrc: '/venue-assets/amour/cake-strawberry.jpg',
      sizes: [{ label: 'M', price: '1000' }, { label: 'L', price: '1200' }],
      i18n: {
        en: { name: 'Strawberry', desc: 'Medium sweet. Sponge cake, strawberry vanilla cream, strawberries on top.' },
        sq: { name: 'Strawberry', desc: 'Mesatarisht e ëmbël. Pandispanjë, krem vanilje me luleshtrydhe, luleshtrydhe sipër.' },
        it: { name: 'Strawberry', desc: 'Mediamente dolce. Pan di Spagna, crema alla vaniglia e fragola, fragole sopra.' },
        pl: { name: 'Strawberry', desc: 'Średnio słodkie. Biszkopt, truskawkowy krem waniliowy, truskawki na wierzchu.' },
        uk: { name: 'Strawberry', desc: 'Помірно солодкий. Бісквіт, полуничний ванільний крем, полуниця зверху.' },
        de: { name: 'Strawberry', desc: 'Mittelsüß. Biskuit, Erdbeer-Vanillecreme, Erdbeeren obenauf.' },
        fr: { name: 'Strawberry', desc: 'Moyennement sucré. Génoise, crème vanille-fraise, fraises dessus.' },
        no: { name: 'Strawberry', desc: 'Middels søt. Sukkerbrød, jordbær-vaniljekrem, jordbær på toppen.' },
      } },
    { id: 'cake-raffaello',  slug: 'cake-raffaello',  price: '1000', posterSrc: '/venue-assets/amour/cake-raffaello.jpg',
      sizes: [{ label: 'M', price: '1000' }, { label: 'L', price: '1200' }],
      i18n: {
        en: { name: 'Raffaello', desc: 'Medium sweet. Sponge cake, vanilla cream, touch of chocolate, Raffaello.' },
        sq: { name: 'Raffaello', desc: 'Mesatarisht e ëmbël. Pandispanjë, krem vanilje, pak çokollatë, Raffaello.' },
        it: { name: 'Raffaello', desc: 'Mediamente dolce. Pan di Spagna, crema alla vaniglia, un tocco di cioccolato, Raffaello.' },
        pl: { name: 'Raffaello', desc: 'Średnio słodkie. Biszkopt, krem waniliowy, odrobina czekolady, Raffaello.' },
        uk: { name: 'Raffaello', desc: 'Помірно солодкий. Бісквіт, ванільний крем, трохи шоколаду, Raffaello.' },
        de: { name: 'Raffaello', desc: 'Mittelsüß. Biskuit, Vanillecreme, ein Hauch Schokolade, Raffaello.' },
        fr: { name: 'Raffaello', desc: 'Moyennement sucré. Génoise, crème vanille, une touche de chocolat, Raffaello.' },
        no: { name: 'Raffaello', desc: 'Middels søt. Sukkerbrød, vaniljekrem, et hint av sjokolade, Raffaello.' },
      } },
  ],
}

const savory: MenuSection = {
  key: 'savory',
  type: 'food',
  views: ['list'],
  i18n: {
    en: { label: 'Snacks' },
    sq: { label: 'Të kripura' },
    it: { label: 'Salati' },
    pl: { label: 'Przekąski' },
    uk: { label: 'Солоне' },
    de: { label: 'Snacks' },
    fr: { label: 'En-cas' },
    no: { label: 'Snacks' },
  },
  items: [
    { id: 'sandwich',   slug: 'sandwich',   price: '150',
      i18n: {
        en: { name: 'Sandwich', desc: 'Salami, tomato.' },
        sq: { name: 'Sandwich', desc: 'Salam, domate.' },
        it: { name: 'Sandwich', desc: 'Salame, pomodoro.' },
        pl: { name: 'Sandwich', desc: 'Salami, pomidor.' },
        uk: { name: 'Sandwich', desc: 'Салямі, помідор.' },
        de: { name: 'Sandwich', desc: 'Salami, Tomate.' },
        fr: { name: 'Sandwich', desc: 'Salami, tomate.' },
        no: { name: 'Sandwich', desc: 'Salami, tomat.' },
      } },
    { id: 'meat-byrek', slug: 'meat-byrek', price: '100',
      i18n: {
        en: { name: 'Meat Byrek', desc: 'Savory filled pastry.' },
        sq: { name: 'Meat Byrek', desc: 'Byrek i mbushur, i kripur.' },
        it: { name: 'Meat Byrek', desc: 'Sfoglia salata ripiena.' },
        pl: { name: 'Meat Byrek', desc: 'Wytrawne nadziewane ciasto.' },
        uk: { name: 'Meat Byrek', desc: 'Солоний пиріг з начинкою.' },
        de: { name: 'Meat Byrek', desc: 'Herzhaftes gefülltes Gebäck.' },
        fr: { name: 'Meat Byrek', desc: 'Feuilleté salé fourré.' },
        no: { name: 'Meat Byrek', desc: 'Salt fylt bakverk.' },
      } },
    { id: 'byrek-veg',  slug: 'byrek-veg',  price: '80',
      i18n: {
        en: { name: 'Byrek', desc: 'Spinach, potato, cheese, tomato.' },
        sq: { name: 'Byrek', desc: 'Spinaq, patate, djathë, domate.' },
        it: { name: 'Byrek', desc: 'Spinaci, patate, formaggio, pomodoro.' },
        pl: { name: 'Byrek', desc: 'Szpinak, ziemniak, ser, pomidor.' },
        uk: { name: 'Byrek', desc: 'Шпинат, картопля, сир, помідор.' },
        de: { name: 'Byrek', desc: 'Spinat, Kartoffel, Käse, Tomate.' },
        fr: { name: 'Byrek', desc: 'Épinards, pomme de terre, fromage, tomate.' },
        no: { name: 'Byrek', desc: 'Spinat, potet, ost, tomat.' },
      } },
  ],
}

// ---------------------------------------------------------------------------

// Dessert → coffee pairings. Rules + rationale live in docs/pairing-rules.md.
// Each dessert lists 3 coffees (best first); `why` is a translation-safe one-liner about coffee #1.
// Pairing quotes, translated once here and reused by both directions (why + wisdom).
// Keep them translation-safe (see docs/pairing-rules.md): literal verbs, no wordplay.
const QUOTES: Record<string, Record<string, string>> = {
  'Bitter cuts the caramel.':      { sq: 'E hidhura pret karamelin.', it: "L'amaro taglia il caramello.", pl: 'Gorycz przełamuje karmel.', uk: 'Гіркота ріже карамель.', de: 'Bitterkeit durchbricht das Karamell.', fr: "L'amertume tranche le caramel.", no: 'Bitterhet kutter karamellen.' },
  'Bitter cuts the chocolate.':    { sq: 'E hidhura pret çokollatën.', it: "L'amaro taglia il cioccolato.", pl: 'Gorycz przełamuje czekoladę.', uk: 'Гіркота ріже шоколад.', de: 'Bitterkeit durchbricht die Schokolade.', fr: "L'amertume tranche le chocolat.", no: 'Bitterhet kutter sjokoladen.' },
  'Bitter cuts the sweetness.':    { sq: 'E hidhura pret ëmbëlsinë.', it: "L'amaro taglia la dolcezza.", pl: 'Gorycz przełamuje słodycz.', uk: 'Гіркота ріже солодкість.', de: 'Bitterkeit durchbricht die Süße.', fr: "L'amertume tranche le sucré.", no: 'Bitterhet kutter sødmen.' },
  'Milk softens the sour berries.':{ sq: 'Qumështi zbut manaferrat e tharta.', it: 'Il latte ammorbidisce i frutti di bosco aspri.', pl: 'Mleko łagodzi kwaśne jagody.', uk: "Молоко пом'якшує кислі ягоди.", de: 'Milch mildert die sauren Beeren.', fr: 'Le lait adoucit les baies acidulées.', no: 'Melk mykner de syrlige bærene.' },
  'Milk softens the sour fruit.':  { sq: 'Qumështi zbut frutin e thartë.', it: 'Il latte ammorbidisce la frutta aspra.', pl: 'Mleko łagodzi kwaśne owoce.', uk: "Молоко пом'якшує кислі фрукти.", de: 'Milch mildert die sauren Früchte.', fr: 'Le lait adoucit les fruits acidulés.', no: 'Melk mykner den syrlige frukten.' },
  'Milk matches the cream.':       { sq: 'Qumështi shkon me kremin.', it: 'Il latte si abbina alla crema.', pl: 'Mleko pasuje do kremu.', uk: 'Молоко пасує до крему.', de: 'Milch passt zur Creme.', fr: "Le lait s'accorde à la crème.", no: 'Melk passer til kremen.' },
  'Milk matches the coconut.':     { sq: 'Qumështi shkon me kokosin.', it: 'Il latte si abbina al cocco.', pl: 'Mleko pasuje do kokosa.', uk: 'Молоко пасує до кокоса.', de: 'Milch passt zur Kokosnuss.', fr: "Le lait s'accorde à la noix de coco.", no: 'Melk passer til kokosen.' },
  'Milk matches the pistachio.':   { sq: 'Qumështi shkon me fëstëkun.', it: 'Il latte si abbina al pistacchio.', pl: 'Mleko pasuje do pistacji.', uk: 'Молоко пасує до фісташки.', de: 'Milch passt zur Pistazie.', fr: "Le lait s'accorde à la pistache.", no: 'Melk passer til pistasjen.' },
  'Espresso matches the cacao.':   { sq: 'Espresso shkon me kakaon.', it: "L'espresso si abbina al cacao.", pl: 'Espresso pasuje do kakao.', uk: 'Еспресо пасує до какао.', de: 'Espresso passt zum Kakao.', fr: "L'espresso s'accorde au cacao.", no: 'Espresso passer til kakaoen.' },
  'Mild coffee suits the apple.':  { sq: 'Kafeja e butë i shkon mollës.', it: 'Un caffè delicato si adatta alla mela.', pl: 'Łagodna kawa pasuje do jabłka.', uk: "М'яка кава пасує до яблука.", de: 'Milder Kaffee passt zum Apfel.', fr: 'Un café doux convient à la pomme.', no: 'Mild kaffe passer til eplet.' },
  'Mild coffee suits the cherry.': { sq: 'Kafeja e butë i shkon qershisë.', it: 'Un caffè delicato si adatta alla ciliegia.', pl: 'Łagodna kawa pasuje do wiśni.', uk: "М'яка кава пасує до вишні.", de: 'Milder Kaffee passt zur Kirsche.', fr: 'Un café doux convient à la cerise.', no: 'Mild kaffe passer til kirsebæret.' },
  'Cold coffee suits the mango.':  { sq: 'Kafeja e ftohtë i shkon mangos.', it: 'Il caffè freddo si adatta al mango.', pl: 'Zimna kawa pasuje do mango.', uk: 'Холодна кава пасує до манго.', de: 'Kalter Kaffee passt zur Mango.', fr: 'Le café froid convient à la mangue.', no: 'Kald kaffe passer til mango.' },
  'Cold coffee suits fruit.':      { sq: 'Kafeja e ftohtë i shkon frutave.', it: 'Il caffè freddo si adatta alla frutta.', pl: 'Zimna kawa pasuje do owoców.', uk: 'Холодна кава пасує до фруктів.', de: 'Kalter Kaffee passt zu Obst.', fr: 'Le café froid convient aux fruits.', no: 'Kald kaffe passer til frukt.' },
}

const whyI18n = (en: string): FoodPairing['i18n'] => {
  const o: FoodPairing['i18n'] = { en: { why: en } }
  for (const loc in QUOTES[en]) o[loc] = { why: QUOTES[en][loc] }
  return o
}
const wisdomI18n = (en: string): Pairing['i18n'] => {
  const o: Pairing['i18n'] = { en: { wisdom: en } }
  for (const loc in QUOTES[en]) o[loc] = { wisdom: QUOTES[en][loc] }
  return o
}

const dessertPairings: FoodPairing[] = [
  { dishRef: 'trilece',         cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the caramel.') },
  { dishRef: 'cheesecake',      cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk softens the sour berries.') },
  { dishRef: 'pastasciutta',    cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the cream.') },
  { dishRef: 'strawberry-d',    cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the cream.') },
  { dishRef: 'millefeuille',    cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the cream.') },
  { dishRef: 'apple',           cocktailRefs: ['americano', 'cappuccino', 'macchiato'],   i18n: whyI18n('Mild coffee suits the apple.') },
  { dishRef: 'mango',           cocktailRefs: ['ice-coffee', 'cappuccino', 'macchiato'],  i18n: whyI18n('Cold coffee suits the mango.') },
  { dishRef: 'lotus',           cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the caramel.') },
  { dishRef: 'tiramisu',        cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Espresso matches the cacao.') },
  { dishRef: 'sacher',          cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the chocolate.') },
  { dishRef: 'ferrero',         cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the sweetness.') },
  { dishRef: 'raffaello',       cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the coconut.') },
  { dishRef: 'red-velvet',      cocktailRefs: ['americano', 'cappuccino', 'macchiato'],   i18n: whyI18n('Mild coffee suits the cherry.') },
  { dishRef: 'mousse',          cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the chocolate.') },
  { dishRef: 'snickers',        cocktailRefs: ['espresso', 'americano', 'macchiato'],   i18n: whyI18n('Bitter cuts the sweetness.') },
  { dishRef: 'panna-cotta',     cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the cream.') },
  { dishRef: 'forest-fruits',   cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk softens the sour fruit.') },
  { dishRef: 'raffaello-paste', cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the coconut.') },
  { dishRef: 'pistachio',       cocktailRefs: ['cappuccino', 'macchiato', 'ice-coffee'], i18n: whyI18n('Milk matches the pistachio.') },
]

// Coffee → dessert pairings (reverse direction; shown on the coffee detail page).
// 3 desserts that best fit each coffee, best first; wisdom follows the same rules as dessert→coffee.
const coffeePairings: Pairing[] = [
  { cocktailRef: 'espresso',   dishes: [{ itemRef: 'tiramisu', price: '200' }, { itemRef: 'sacher', price: '200' }, { itemRef: 'mousse', price: '200' }],        i18n: wisdomI18n('Bitter cuts the sweetness.') },
  { cocktailRef: 'americano',  dishes: [{ itemRef: 'trilece', price: '150' }, { itemRef: 'lotus', price: '250' }, { itemRef: 'ferrero', price: '200' }],           i18n: wisdomI18n('Bitter cuts the sweetness.') },
  { cocktailRef: 'macchiato',  dishes: [{ itemRef: 'pastasciutta', price: '100' }, { itemRef: 'millefeuille', price: '150' }, { itemRef: 'pistachio', price: '300' }], i18n: wisdomI18n('Milk matches the cream.') },
  { cocktailRef: 'cappuccino', dishes: [{ itemRef: 'cheesecake', price: '350' }, { itemRef: 'raffaello', price: '200' }, { itemRef: 'panna-cotta', price: '200' }],  i18n: wisdomI18n('Milk matches the cream.') },
  { cocktailRef: 'ice-coffee', dishes: [{ itemRef: 'mango', price: '300' }, { itemRef: 'cheesecake', price: '350' }, { itemRef: 'strawberry-d', price: '300' }],     i18n: wisdomI18n('Cold coffee suits fruit.') },
]

export const amourMenuData: VenueMenuData = applyCoffeeTastes(
  applyPlaceholders(
    {
      currency: 'L',
      sections: [coffee, drinks],
      foodSections: [desserts, cakes, savory],
      pairings: coffeePairings,
      foodPairings: dessertPairings,
      featuredPick: { cocktailRef: '' },
    },
    PLACEHOLDERS,
  ),
)
