import type { MenuSection, VenueMenuData } from './menu-data'

// ---------------------------------------------------------------------------
// Côte Durrës — menu data
// Source: menu photo parse 2026-06-23. Prices in Albanian Lek (ALL / L).
// ⚠️  Vanilla + Chocolate waffle/crêpe: names and prices inferred from photo
//     (right edge cut off). Confirm with client before going live.
// ---------------------------------------------------------------------------

// ── DRINKS ── (go in sections → shown in left category tab) ─────────────────

const hotDrinks: MenuSection = {
  key: 'hot-drinks',
  type: 'cocktail',
  i18n: {
    en: { label: 'Hot drinks' },
    sq: { label: 'Pije të ngrohta' },
    it: { label: 'Calde' },
    pl: { label: 'Ciepłe napoje' },
    hu: { label: 'Meleg italok' },
    de: { label: 'Heiße Getränke' },
    fr: { label: 'Boissons chaudes' },
    no: { label: 'Varme drikker' },
  },
  items: [
    { id: 'espresso',            slug: 'espresso',            price: 'L90',
      i18n: { en: { name: 'Espresso',                  desc: 'Short, strong, the classic.' } } },
    { id: 'macchiato',           slug: 'macchiato',           price: 'L100',
      i18n: { en: { name: 'Macchiato',                 desc: 'Espresso with a dash of hot foamed milk.' } } },
    { id: 'decaffeinato',        slug: 'decaffeinato',        price: 'L100',
      i18n: { en: { name: 'Decaffeinato',              desc: 'All the ritual, none of the buzz.' } } },
    { id: 'latte-macchiato',     slug: 'latte-macchiato',     price: 'L200',
      i18n: { en: { name: 'Latte Macchiato',           desc: 'Warm milk, espresso poured slowly through.' } } },
    { id: 'americano',           slug: 'americano',           price: 'L100',
      i18n: { en: { name: 'Americano',                 desc: 'Espresso stretched with hot water.' } } },
    { id: 'cappuccino',          slug: 'cappuccino',          price: 'L200',
      i18n: { en: { name: 'Cappuccino',                desc: 'Equal parts espresso, steamed milk, foam.' } } },
    { id: 'hot-chocolate',       slug: 'hot-chocolate',       price: 'L200',
      i18n: { en: { name: 'Hot Chocolate',             desc: 'Rich and warming, made with real chocolate.' } } },
    { id: 'hot-tea',             slug: 'hot-tea',             price: 'L100',
      i18n: { en: { name: 'Hot Tea',                   desc: 'A selection of classic teas.' } } },
    { id: 'bio-tea',             slug: 'bio-tea',             price: 'L150',
      i18n: { en: { name: 'Bio Tea',                   desc: 'Organic loose-leaf blends, brewed properly.' } } },
    { id: 'salep',               slug: 'salep',               price: 'L150',
      i18n: { en: { name: 'Salep',                     desc: 'Warm orchid-flour drink, a seaside winter staple.' } } },
    { id: 'min-cacao',           slug: 'min-cacao',           price: 'L100',
      i18n: { en: { name: 'Min Cacao',                 desc: 'Small cup of warm cacao.' } } },
    { id: 'cacao',               slug: 'cacao',               price: 'L150',
      i18n: { en: { name: 'Cacao',                     desc: 'Full cup of warm cacao, rich and smooth.' } } },
    { id: 'irish-french-coffee', slug: 'irish-french-coffee', price: 'L450',
      i18n: { en: { name: 'Irish Coffee / French Coffee', desc: 'Coffee with whiskey or cognac, finished with whipped cream.' } } },
  ],
}

const coldCoffees: MenuSection = {
  key: 'cold-coffees',
  type: 'cocktail',
  i18n: {
    en: { label: 'Cold coffees' },
    sq: { label: 'Kafe të ftohta' },
    it: { label: 'Caffè freddi' },
    pl: { label: 'Zimne kawy' },
    hu: { label: 'Hideg kávék' },
    de: { label: 'Eiskaffee' },
    fr: { label: 'Cafés glacés' },
    no: { label: 'Kald kaffe' },
  },
  items: [
    { id: 'freddo-espresso',   slug: 'freddo-espresso',   price: 'L200',
      i18n: { en: { name: 'Freddo Espresso',   desc: 'Double espresso shaken over ice.' } } },
    { id: 'freddo-macchiato',  slug: 'freddo-macchiato',  price: 'L250',
      i18n: { en: { name: 'Freddo Macchiato',  desc: 'Freddo espresso with cold foamed milk.' } } },
    { id: 'frappe',            slug: 'frappe',            price: 'L250',
      i18n: { en: { name: 'Frappé',            desc: 'Blended iced coffee, smooth and creamy.' } } },
    { id: 'freddo-cappuccino', slug: 'freddo-cappuccino', price: 'L250',
      i18n: { en: { name: 'Freddo Cappuccino', desc: 'Chilled espresso, cold milk foam.' } } },
    { id: 'freddo-chocolate',  slug: 'freddo-chocolate',  price: 'L250',
      i18n: { en: { name: 'Freddo Chocolate',  desc: 'Cold chocolate drink, blended over ice.' } } },
  ],
}

const softDrinks: MenuSection = {
  key: 'soft-drinks',
  type: 'cocktail',
  i18n: {
    en: { label: 'Soft drinks' },
    sq: { label: 'Pije joalkoolike' },
    it: { label: 'Analcolici' },
    pl: { label: 'Napoje' },
    hu: { label: 'Üdítők' },
    de: { label: 'Softdrinks' },
    fr: { label: 'Sodas' },
    no: { label: 'Brus' },
  },
  items: [
    { id: 'water',             slug: 'water',             price: 'L100',
      i18n: { en: { name: 'Water',                   desc: 'Still mineral water.' } } },
    { id: 'bitter',            slug: 'bitter',            price: 'L100',
      i18n: { en: { name: 'Bitter',                  desc: 'Italian non-alcoholic bitter aperitif soda.' } } },
    { id: 'vitamins-water',    slug: 'vitamins-water',    price: 'L150',
      i18n: { en: { name: 'Vitamins Water',          desc: 'Lightly flavored water with added vitamins.' } } },
    { id: 'energy-drink',      slug: 'energy-drink',      price: 'L250',
      i18n: { en: { name: 'Energy Drink',            desc: 'B52 energy drink, 250ml.' } } },
    { id: 'bravo',             slug: 'bravo',             price: 'L200',
      i18n: { en: { name: 'Bravo',                   desc: 'Lightly sparkling fruit drink.' } } },
    { id: 'iced-tea',          slug: 'iced-tea',          price: 'L200',
      i18n: { en: { name: 'Iced Tea',                desc: 'Chilled brewed tea.' } } },
    { id: 'coca-cola',         slug: 'coca-cola',         price: 'L200',
      i18n: { en: { name: 'Coca-Cola',               desc: 'The classic.' } } },
    { id: 'fanta',             slug: 'fanta',             price: 'L200',
      i18n: { en: { name: 'Fanta',                   desc: 'Orange fruit soda.' } } },
    { id: 'crodino',           slug: 'crodino',           price: 'L150',
      i18n: { en: { name: 'Crodino',                 desc: 'Italian non-alcoholic aperitif, bittersweet.' } } },
    { id: 'orange-lemon-soda', slug: 'orange-lemon-soda', price: 'L200',
      i18n: { en: { name: 'Orange & Lemon Soda',     desc: 'Fresh citrus soda.' } } },
    { id: 'sprite',            slug: 'sprite',            price: 'L200',
      i18n: { en: { name: 'Sprite',                  desc: 'Lemon-lime soda.' } } },
    { id: 'tonic-water',       slug: 'tonic-water',       price: 'L200',
      i18n: { en: { name: 'Tonic Water',             desc: 'Dry sparkling tonic.' } } },
    { id: 'nescafe',           slug: 'nescafe',           price: 'L200',
      i18n: { en: { name: 'Nescafé',                 desc: 'Iced instant coffee.' } } },
    { id: 'red-bull',          slug: 'red-bull',          price: 'L350',
      i18n: { en: { name: 'Red Bull',                desc: 'Energy drink, 250ml.' } } },
    { id: 'rose-lemonade',     slug: 'rose-lemonade',     price: 'L450',
      i18n: { en: { name: 'Rose Lemonade',           desc: 'Lemonade with rose syrup and fresh notes.' } } },
    { id: 'smoothie',          slug: 'smoothie',          price: 'L350',
      i18n: { en: { name: 'Smoothie',                desc: 'Blended seasonal fruits.' } } },
    { id: 'milkshake',         slug: 'milkshake',         price: 'L350',
      i18n: { en: { name: 'Milkshake',               desc: 'Thick blended milk and ice cream.' } } },
  ],
}

const bioJuices: MenuSection = {
  key: 'bio-juices',
  type: 'cocktail',
  i18n: {
    en: { label: 'Bio juices' },
    sq: { label: 'Lëngje bio' },
    it: { label: 'Succhi bio' },
    pl: { label: 'Soki bio' },
    hu: { label: 'Bio gyümölcslevek' },
    de: { label: 'Bio-Säfte' },
    fr: { label: 'Jus bio' },
    no: { label: 'Bio-juice' },
  },
  items: [
    { id: 'apple-juice-bio',  slug: 'apple-juice-bio',  price: 'L300',
      i18n: { en: { name: 'Apple Juice Bio',  desc: 'Cold-pressed organic apple.' } } },
    { id: 'orange-juice-bio', slug: 'orange-juice-bio', price: 'L300',
      i18n: { en: { name: 'Orange Juice Bio', desc: 'Organic orange, freshly pressed.' } } },
    { id: 'mixed-juice-bio',  slug: 'mixed-juice-bio',  price: 'L300',
      i18n: { en: { name: 'Mixed Juice Bio',  desc: 'Organic blend of seasonal fruits.' } } },
  ],
}

const beers: MenuSection = {
  key: 'beers',
  type: 'cocktail',
  i18n: {
    en: { label: 'Beers' },
    sq: { label: 'Birra' },
    it: { label: 'Birre' },
    pl: { label: 'Piwa' },
    hu: { label: 'Sörök' },
    de: { label: 'Bier' },
    fr: { label: 'Bières' },
    no: { label: 'Øl' },
  },
  items: [
    { id: 'beer-zero',          slug: 'beer-zero',          price: 'L250',
      i18n: { en: { name: '0% Alcohol Beer',    desc: 'Full flavor without the alcohol.' } } },
    { id: 'peroni',             slug: 'peroni',             price: 'L350',
      i18n: { en: { name: 'Peroni',             desc: 'Italian lager, crisp and clean.' } } },
    { id: 'korca',              slug: 'korca',              price: 'L350',
      i18n: { en: { name: 'Korça',              desc: 'Albanian lager, light and refreshing.' } } },
    { id: 'heineken',           slug: 'heineken',           price: 'L400',
      i18n: { en: { name: 'Heineken',           desc: 'Dutch lager, a worldwide classic.' } } },
    { id: 'corona',             slug: 'corona',             price: 'L350',
      i18n: { en: { name: 'Corona',             desc: 'Mexican lager, best with a wedge of lime.' } } },
    { id: 'paulaner-kristall',  slug: 'paulaner-kristall',  price: 'L450',
      i18n: { en: { name: 'Paulaner Kristall',  desc: 'Bavarian wheat beer, filtered and clear.' } } },
    { id: 'paulaner-weissbier', slug: 'paulaner-weissbier', price: 'L450',
      i18n: { en: { name: 'Paulaner Weissbier', desc: 'Unfiltered Bavarian wheat beer, full and cloudy.' } } },
  ],
}

const wine: MenuSection = {
  key: 'wine',
  type: 'cocktail',
  i18n: {
    en: { label: 'Wine & Prosecco', sub: '125 ml · Bottle 2,500' },
    sq: { label: 'Verë & Prosecco', sub: '125 ml · Shishe 2,500' },
    it: { label: 'Vino & Prosecco', sub: '125 ml · Bottiglia 2.500' },
    pl: { label: 'Wino & Prosecco', sub: '125 ml · Butelka 2 500' },
    hu: { label: 'Bor & Prosecco',  sub: '125 ml · Üveg 2 500' },
    de: { label: 'Wein & Prosecco', sub: '125 ml · Flasche 2.500' },
    fr: { label: 'Vin & Prosecco',  sub: '125 ml · Bouteille 2 500' },
    no: { label: 'Vin & Prosecco',  sub: '125 ml · Flaske 2 500' },
  },
  items: [
    { id: 'prosecco',           slug: 'prosecco',           price: 'L450',
      i18n: { en: { name: 'Prosecco',           desc: 'Italian sparkling wine, light and dry.' } } },
    { id: 'pinot-grigio',       slug: 'pinot-grigio',       price: 'L450',
      i18n: { en: { name: 'Pinot Grigio',       desc: 'Crisp white wine, notes of green apple and citrus.' } } },
    { id: 'pinot-grigio-blush', slug: 'pinot-grigio-blush', price: 'L450',
      i18n: { en: { name: 'Pinot Grigio Blush', desc: 'Soft rosé, delicate summer fruit.' } } },
    { id: 'merlot',             slug: 'merlot',             price: 'L450',
      i18n: { en: { name: 'Merlot',             desc: 'Round red wine, soft tannins and dark fruit.' } } },
  ],
}

const cocktails: MenuSection = {
  key: 'cocktails',
  type: 'cocktail',
  i18n: {
    en: { label: 'Cocktails', note: 'Any 2 of the same · 1,200' },
    sq: { label: 'Kokteje',   note: '2 të njëjtat · 1,200' },
    it: { label: 'Cocktail',  note: '2 uguali · 1.200' },
    pl: { label: 'Koktajle',  note: '2 takie same · 1 200' },
    hu: { label: 'Koktélok',  note: '2 ugyanolyan · 1 200' },
    de: { label: 'Cocktails', note: '2 gleiche · 1.200' },
    fr: { label: 'Cocktails', note: '2 identiques · 1 200' },
    no: { label: 'Cocktails', note: '2 like · 1 200' },
  },
  items: [
    { id: 'cote-mojito',           slug: 'cote-mojito',           price: 'L700',
      i18n: { en: { name: 'Mojito',               desc: 'White rum, fresh lime and mint, soda water and brown sugar.' } } },
    { id: 'cote-margarita',        slug: 'cote-margarita',        price: 'L700',
      i18n: { en: { name: 'Margarita',            desc: 'Tequila, triple sec, lime juice.' } } },
    { id: 'cote-sex-beach',        slug: 'cote-sex-beach',        price: 'L700',
      i18n: { en: { name: 'Sex on the Beach',     desc: 'Peach schnapps, vodka, orange juice and grenadine.' } } },
    { id: 'cote-pina-colada',      slug: 'cote-pina-colada',      price: 'L700',
      i18n: { en: { name: 'Piña Colada',          desc: 'White rum, coconut cream, fresh pineapple and Malibu.' } } },
    { id: 'cote-pornstar-martini', slug: 'cote-pornstar-martini', price: 'L700',
      i18n: { en: { name: 'Pornstar Martini',     desc: 'Vanilla vodka, vanilla syrup, passion fruit, fresh lime and a shot of prosecco.' } } },
    { id: 'cote-espresso-martini', slug: 'cote-espresso-martini', price: 'L700',
      i18n: { en: { name: 'Espresso Martini',     desc: 'Kahlúa, espresso coffee and vodka.' } } },
    { id: 'cote-negroni',          slug: 'cote-negroni',          price: 'L700',
      i18n: { en: { name: 'Negroni',              desc: 'Gin, Campari, Martini Rosso and a slice of fresh orange.' } } },
    { id: 'cote-tequila-sunrise',  slug: 'cote-tequila-sunrise',  price: 'L700',
      i18n: { en: { name: 'Tequila Sunrise',      desc: 'Tequila and Cointreau, blend of orange and lemon juice, topped with grenadine and a cherry.' } } },
    { id: 'cote-amaretto-sour',    slug: 'cote-amaretto-sour',    price: 'L700',
      i18n: { en: { name: 'Amaretto Sour',        desc: 'Disaronno shaken with lemon juice, topped with egg white and a cherry.' } } },
    { id: 'cote-long-island',      slug: 'cote-long-island',      price: 'L700',
      i18n: { en: { name: 'Long Island Iced Tea', desc: 'Vodka, white rum, gin, triple sec, lime juice and Coke.' } } },
    { id: 'cote-aperol-spritz',    slug: 'cote-aperol-spritz',    price: 'L700',
      i18n: { en: { name: 'Aperol Spritz',        desc: 'Aperol, prosecco and soda water.' } } },
    { id: 'cote-whiskey-sour',     slug: 'cote-whiskey-sour',     price: 'L700',
      i18n: { en: { name: 'Whiskey Sour',         desc: 'Whiskey shaken with lemon juice, topped with egg white and a cherry.' } } },
    { id: 'cote-strawberry-punch', slug: 'cote-strawberry-punch', price: 'L700',
      i18n: { en: { name: 'Strawberry Punch',     desc: 'Pink gin, prosecco, grenadine and fresh strawberries.' } } },
    { id: 'cote-zombie',           slug: 'cote-zombie',           price: 'L900', badge: 'Double 1,600',
      i18n: { en: { name: 'Zombie',               desc: 'Gold and white rum, orange liquor, lime, vanilla syrup and pineapple juice.' } } },
  ],
}

// ── FOOD ── (go in foodSections → shown in right category tab) ──────────────

const breakfast: MenuSection = {
  key: 'breakfast',
  type: 'food',
  i18n: {
    en: { label: 'Breakfast', sub: 'Until 3 pm',
      note: '+ extras: Sausage 100 · Meatballs 100 · Avocado 200 · Bacon 100 · Cheese 150 · Hollandaise 150' },
    sq: { label: 'Mëngjes',        sub: 'Deri në 15:00' },
    it: { label: 'Colazione',      sub: 'Fino alle 15:00' },
    pl: { label: 'Śniadanie',      sub: 'Do 15:00' },
    hu: { label: 'Reggeli',        sub: '15:00-ig' },
    de: { label: 'Frühstück',      sub: 'Bis 15:00 Uhr' },
    fr: { label: 'Petit-déjeuner', sub: "Jusqu'à 15h" },
    no: { label: 'Frokost',        sub: 'Til kl. 15:00' },
  },
  items: [
    { id: 'fruit-salad',             slug: 'fruit-salad',             price: 'L500',
      i18n: { en: { name: 'Fruit Salad',               desc: 'Mixed seasonal fruits.' } } },
    { id: 'granola-yogurt',          slug: 'granola-yogurt',          price: 'L550',
      i18n: { en: { name: 'Granola & Greek Yogurt',    desc: 'Greek yogurt, granola, fresh fruits.' } } },
    { id: 'crepe-complete',          slug: 'crepe-complete',          price: 'L650',
      i18n: { en: { name: 'Crêpe Complete',            desc: 'Crêpe with ham, cheese and egg.' } } },
    { id: 'bacon-sausage-breakfast', slug: 'bacon-sausage-breakfast', price: 'L700',
      i18n: { en: { name: 'Bacon & Sausage',           desc: 'Toasted bread, scrambled eggs, cheese, sausage, bacon, fresh tomato.' } } },
    { id: 'smoked-salmon-breakfast', slug: 'smoked-salmon-breakfast', price: 'L800',
      i18n: { en: { name: 'Smoked Salmon',             desc: 'Toasted bread, scrambled eggs, cheese, smoked salmon.' } } },
    { id: 'vegetarian-breakfast',    slug: 'vegetarian-breakfast',    price: 'L600',
      i18n: { en: { name: 'Vegetarian',                desc: 'Toasted bread, scrambled eggs, cheese, fresh fruits.' } } },
    { id: 'omelette-ham-cheese',     slug: 'omelette-ham-cheese',     price: 'L600',
      i18n: { en: { name: 'Omelette with Ham & Cheese', desc: 'Served with toast.' } } },
    { id: 'french-toast',            slug: 'french-toast',            price: 'L600',
      i18n: { en: { name: 'French Toast',              desc: 'Toasted brioche, seasonal fruits, honey, Greek yogurt.' } } },
    { id: 'french-toast-platter',    slug: 'french-toast-platter',    price: 'L850',
      i18n: { en: { name: 'French Toast Platter',      desc: 'Toasted brioche, seasonal fruits, honey, scrambled eggs and bacon.' } } },
  ],
}

const sandwiches: MenuSection = {
  key: 'sandwiches',
  type: 'food',
  i18n: {
    en: { label: 'Sandwiches', sub: 'Until 3 pm' },
    sq: { label: 'Sanduiçe',   sub: 'Deri në 15:00' },
    it: { label: 'Panini',     sub: 'Fino alle 15:00' },
    pl: { label: 'Kanapki',    sub: 'Do 15:00' },
    hu: { label: 'Szendvicsek', sub: '15:00-ig' },
    de: { label: 'Sandwiches', sub: 'Bis 15:00 Uhr' },
    fr: { label: 'Sandwichs',  sub: "Jusqu'à 15h" },
    no: { label: 'Smørbrød',   sub: 'Til kl. 15:00' },
  },
  items: [
    { id: 'ham-cheese-sandwich', slug: 'ham-cheese-sandwich', price: 'L250',
      i18n: { en: { name: 'Ham & Cheese',   desc: 'Ham, cheese and mayonnaise.' } } },
    { id: 'tuna-sandwich',       slug: 'tuna-sandwich',       price: 'L350',
      i18n: { en: { name: 'Tuna',           desc: 'Mayonnaise, red onion, sweetcorn and rocket.' } } },
    { id: 'vegetarian-sandwich', slug: 'vegetarian-sandwich', price: 'L250',
      i18n: { en: { name: 'Vegetarian',     desc: 'Lettuce, tomato, cucumber and mayonnaise.' } } },
    { id: 'meatball-sandwich',   slug: 'meatball-sandwich',   price: 'L250',
      i18n: { en: { name: 'Meatball',       desc: 'Meatballs and tzatziki.' } } },
  ],
}

const salads: MenuSection = {
  key: 'salads',
  type: 'food',
  i18n: {
    en: { label: 'Salads' },
    sq: { label: 'Sallatat' },
    it: { label: 'Insalate' },
    pl: { label: 'Sałatki' },
    hu: { label: 'Saláták' },
    de: { label: 'Salate' },
    fr: { label: 'Salades' },
    no: { label: 'Salater' },
  },
  items: [
    { id: 'caprese-salad',  slug: 'caprese-salad',  price: 'L550',
      i18n: { en: { name: 'Caprese',              desc: 'Tomato and mozzarella.' } } },
    { id: 'greek-salad',    slug: 'greek-salad',    price: 'L500',
      i18n: { en: { name: 'Greek Salad',          desc: 'Tomato, cucumber, olives and onion.' } } },
    { id: 'caesar-chicken', slug: 'caesar-chicken', price: 'L800',
      i18n: { en: { name: 'Caesar with Chicken',  desc: 'Lettuce, Caesar dressing, egg, croutons, chicken breast.' } } },
  ],
}

const smallPlates: MenuSection = {
  key: 'small-plates',
  type: 'food',
  i18n: {
    en: { label: 'Small plates', note: 'Any 3 for 1,500 · Sauce +150: Tzatziki / Pepper Salsa / BBQ / Garlic Mayo' },
    sq: { label: 'Pjata të vogla', note: '3 çfarëdo për 1,500 · Salcë +150: Tzatziki / Speca / BBQ / Hudhër majonezë' },
    it: { label: 'Piatti piccoli', note: '3 a scelta per 1.500 · Salsa +150: Tzatziki / Peperoni / BBQ / Aglio mayo' },
    pl: { label: 'Małe dania',     note: 'Dowolne 3 za 1 500 · Sos +150: Tzatziki / Paprykowa / BBQ / Czosnkowy' },
    hu: { label: 'Kis fogások',    note: 'Bármilyen 3 darab 1 500-ért · Szósz +150: Tzatziki / Paprika / BBQ / Fokhagymás' },
    de: { label: 'Kleine Gerichte', note: 'Beliebige 3 für 1.500 · Sauce +150: Tzatziki / Paprika / BBQ / Knoblauch-Mayo' },
    fr: { label: 'Petits plats',   note: "3 au choix pour 1 500 · Sauce +150 : Tzatziki / Poivron / BBQ / Mayo ail" },
    no: { label: 'Smårett',        note: '3 valgfrie for 1 500 · Saus +150: Tzatziki / Pepper / BBQ / Hvitløksmajo' },
  },
  items: [
    { id: 'bread-olives',          slug: 'bread-olives',          price: 'L400',
      i18n: { en: { name: 'Bread & Olives',                       desc: 'House bread, warm from the oven, with marinated olives.' } } },
    { id: 'bruschetta-pomodoro',   slug: 'bruschetta-pomodoro',   price: 'L400',
      i18n: { en: { name: 'Bruschetta Pomodoro',                  desc: 'Toasted bread, ripe tomatoes, fresh basil, olive oil.' } } },
    { id: 'sp-greek-salad',        slug: 'sp-greek-salad',        price: 'L400',
      i18n: { en: { name: 'Greek Salad',                          desc: 'Tomato, cucumber, olives and onion.' } } },
    { id: 'sp-caesar-salad',       slug: 'sp-caesar-salad',       price: 'L400',
      i18n: { en: { name: 'Caesar Salad',                         desc: 'Lettuce, Caesar dressing, egg, croutons, chicken breast.' } } },
    { id: 'garlic-prawns',         slug: 'garlic-prawns',         price: 'L400',
      i18n: { en: { name: 'Garlic Prawns',                        desc: 'Pan-fried prawns with garlic and parsley.' } } },
    { id: 'meatballs-tomato',      slug: 'meatballs-tomato',      price: 'L400',
      i18n: { en: { name: 'Meatballs in Tomato Sauce',            desc: 'Slow-cooked in a rich tomato sauce.' } } },
    { id: 'seafood-garlic-tomato', slug: 'seafood-garlic-tomato', price: 'L400',
      i18n: { en: { name: 'Seafood Mix in Garlic & Tomato',       desc: 'Prawns, mussels and calamari, sautéed.' } } },
    { id: 'paprika-potatoes',      slug: 'paprika-potatoes',      price: 'L400',
      i18n: { en: { name: 'Paprika Potatoes',                     desc: 'Crispy potatoes with smoked paprika.' } } },
    { id: 'spanish-omelette',      slug: 'spanish-omelette',      price: 'L400',
      i18n: { en: { name: 'Spanish Omelette',                     desc: 'Thick potato and egg omelette, served warm.' } } },
    { id: 'spicy-sausage',         slug: 'spicy-sausage',         price: 'L400',
      i18n: { en: { name: 'Spicy Sausage',                        desc: 'Grilled with a kick of chili.' } } },
    { id: 'cassoulet-lamb',        slug: 'cassoulet-lamb',        price: 'L400',
      i18n: { en: { name: 'Cassoulet with Lamb',                  desc: 'Slow-braised lamb with white beans.' } } },
    { id: 'asian-beef',            slug: 'asian-beef',            price: 'L400',
      i18n: { en: { name: 'Asian Beef',                           desc: 'Tender beef strips in a sweet-savory Asian sauce.' } } },
    { id: 'salmon-lemon',          slug: 'salmon-lemon',          price: 'L800', badge: '+400 surcharge',
      i18n: { en: { name: 'Salmon Fillet with Lemon',             desc: 'Pan-seared salmon, lemon butter and herbs.' } } },
    { id: 'chicken-strips',        slug: 'chicken-strips',        price: 'L400',
      i18n: { en: { name: 'Chicken Strips',                       desc: 'Crispy fried chicken strips.' } } },
    { id: 'grilled-peppers',       slug: 'grilled-peppers',       price: 'L400',
      i18n: { en: { name: 'Grilled Peppers',                      desc: 'Charred sweet peppers, olive oil.' } } },
    { id: 'steamed-veg',           slug: 'steamed-veg',           price: 'L400',
      i18n: { en: { name: 'Steamed Vegetables with Olive Oil',    desc: 'Seasonal vegetables, light and clean.' } } },
    { id: 'rice',                  slug: 'rice',                  price: 'L400',
      i18n: { en: { name: 'Rice',                                 desc: 'Plain steamed rice.' } } },
  ],
}

const pastries: MenuSection = {
  key: 'pastries',
  type: 'food',
  i18n: {
    en: { label: 'Pastries' },
    sq: { label: 'Ëmbëlsira' },
    it: { label: 'Dolci' },
    pl: { label: 'Ciastka' },
    hu: { label: 'Sütemények' },
    de: { label: 'Gebäck' },
    fr: { label: 'Pâtisseries' },
    no: { label: 'Bakverk' },
  },
  items: [
    { id: 'croissants',       slug: 'croissants',       price: 'L150',
      i18n: { en: { name: 'Selection of Croissants', desc: 'Freshly baked daily. Choose from Chocolate, Pistachio or Crème.' } } },
    { id: 'pastry-selection', slug: 'pastry-selection', price: 'L300',
      i18n: { en: { name: 'Selection of Pastries',   desc: 'Choose from Snickers, Kinder, Lemon, Cipriani, Lacta or Amanda.' } } },
    { id: 'cheesecake',       slug: 'cheesecake',       price: 'L280',
      i18n: { en: { name: 'Cheesecake',              desc: 'Smooth and creamy, baked on a classic biscuit base.' } } },
    { id: 'kamelia-lotus',    slug: 'kamelia-lotus',    price: 'L320',
      i18n: { en: { name: 'Kamelia – Lotus',         desc: 'Layered cake with Lotus biscuit cream and salted caramel.' } } },
    { id: 'ekmek-tiramisu',   slug: 'ekmek-tiramisu',   price: 'L250',
      i18n: { en: { name: 'Ekmek – Tiramisu',        desc: 'Choose between syrup-soaked semolina pastry or classic Italian tiramisu.' } } },
    { id: 'pastashu',         slug: 'pastashu',         price: 'L180',
      i18n: { en: { name: 'Pastashu',                desc: 'Light choux pastry filled with vanilla cream.' } } },
    { id: 'zup',              slug: 'zup',              price: 'L220',
      i18n: { en: { name: 'Zup',                     desc: 'Traditional Albanian cream pastry, delicate and lightly sweet.' } } },
    { id: 'cannoli',          slug: 'cannoli',          price: 'L180',
      i18n: { en: { name: 'Cannoli',                 desc: 'Crisp pastry shells filled with sweet ricotta.' } } },
  ],
}

const waffles: MenuSection = {
  key: 'waffles',
  type: 'food',
  i18n: {
    en: { label: 'Waffles' },
    sq: { label: 'Wafla' },
    it: { label: 'Cialde' },
    pl: { label: 'Gofry' },
    hu: { label: 'Gofrik' },
    de: { label: 'Waffeln' },
    fr: { label: 'Gaufres' },
    no: { label: 'Vafler' },
  },
  items: [
    { id: 'waffle-dubai',     slug: 'waffle-dubai',     price: 'L850',
      i18n: { en: { name: 'Dubai',                   desc: 'Nutella, pistachio sauce, kadaif and pistachio ice cream.' } } },
    { id: 'waffle-royale',    slug: 'waffle-royale',    price: 'L550',
      i18n: { en: { name: 'Royale',                  desc: 'Nutella, hazelnuts, hazelnut chocolate truffle, chocolate ice cream and whipped cream.' } } },
    { id: 'waffle-pink',      slug: 'waffle-pink',      price: 'L550',
      i18n: { en: { name: 'Pink',                    desc: 'Warm white chocolate sauce, chocolate shavings, strawberry ice cream and whipped cream.' } } },
    { id: 'waffle-pistachio', slug: 'waffle-pistachio', price: 'L600',
      i18n: { en: { name: 'Pistachio',               desc: 'Warm milk and white chocolate sauce, crushed pistachio, pistachio ice cream and whipped cream.' } } },
    { id: 'waffle-lotus',     slug: 'waffle-lotus',     price: 'L550',
      i18n: { en: { name: 'Lotus',                   desc: 'Warm Lotus sauce, crushed lotus biscuits, Lotus ice cream and whipped cream.' } } },
    { id: 'waffle-banana',    slug: 'waffle-banana',    price: 'L550',
      i18n: { en: { name: 'Banana',                  desc: 'Warm caramel and white chocolate sauce, banana, torched marshmallows, vanilla ice cream and whipped cream.' } } },
    { id: 'waffle-passion',   slug: 'waffle-passion',   price: 'L550',
      i18n: { en: { name: 'Passion Fruit & Pineapple', desc: 'Caramel sauce, caramelised cinnamon pineapple, hazelnuts, passion fruit ice cream and cream.' } } },
    { id: 'waffle-flambee',   slug: 'waffle-flambee',   price: 'L750',
      i18n: { en: { name: 'Flambée',                 desc: 'Fresh orange juice, fresh orange, Grand Marnier, vanilla ice cream and whipped cream.' } } },
    // TODO: confirm name and price — photo cut off right edge
    { id: 'waffle-vanilla',   slug: 'waffle-vanilla',   price: 'L550',
      i18n: { en: { name: 'Vanilla',                 desc: 'Warm vanilla cream, vanilla ice cream and whipped cream.' } } },
    { id: 'waffle-chocolate', slug: 'waffle-chocolate', price: 'L550',
      i18n: { en: { name: 'Chocolate',               desc: 'Warm dark chocolate sauce, chocolate ice cream and whipped cream.' } } },
  ],
}

const crepes: MenuSection = {
  key: 'crepes',
  type: 'food',
  i18n: {
    en: { label: 'Crêpes' },
    sq: { label: 'Krep' },
    it: { label: 'Crêpes' },
    pl: { label: 'Naleśniki' },
    hu: { label: 'Palacsinta' },
    de: { label: 'Crêpes' },
    fr: { label: 'Crêpes' },
    no: { label: 'Pannekaker' },
  },
  items: [
    { id: 'crepe-dubai',     slug: 'crepe-dubai',     price: 'L800',
      i18n: { en: { name: 'Dubai',                   desc: 'Nutella, pistachio sauce, kadaif and pistachio ice cream.' } } },
    { id: 'crepe-royale',    slug: 'crepe-royale',    price: 'L500',
      i18n: { en: { name: 'Royale',                  desc: 'Nutella, hazelnuts, hazelnut chocolate truffle, chocolate ice cream and whipped cream.' } } },
    { id: 'crepe-pink',      slug: 'crepe-pink',      price: 'L500',
      i18n: { en: { name: 'Pink',                    desc: 'Warm white chocolate sauce, chocolate shavings, strawberry ice cream and whipped cream.' } } },
    { id: 'crepe-pistachio', slug: 'crepe-pistachio', price: 'L550',
      i18n: { en: { name: 'Pistachio',               desc: 'Warm milk and white chocolate sauce, crushed pistachio, pistachio ice cream and whipped cream.' } } },
    { id: 'crepe-lotus',     slug: 'crepe-lotus',     price: 'L500',
      i18n: { en: { name: 'Lotus',                   desc: 'Warm Lotus sauce, crushed lotus biscuits, Lotus ice cream and whipped cream.' } } },
    { id: 'crepe-banana',    slug: 'crepe-banana',    price: 'L500',
      i18n: { en: { name: 'Banana',                  desc: 'Warm caramel and white chocolate sauce, banana, torched marshmallows, vanilla ice cream and whipped cream.' } } },
    { id: 'crepe-passion',   slug: 'crepe-passion',   price: 'L500',
      i18n: { en: { name: 'Passion Fruit & Pineapple', desc: 'Caramel sauce, caramelised cinnamon pineapple, hazelnuts, passion fruit ice cream and cream.' } } },
    { id: 'crepe-flambee',   slug: 'crepe-flambee',   price: 'L700',
      i18n: { en: { name: 'Flambée',                 desc: 'Fresh orange juice, fresh orange, Grand Marnier, vanilla ice cream and whipped cream.' } } },
    // TODO: confirm name and price — photo cut off right edge
    { id: 'crepe-vanilla',   slug: 'crepe-vanilla',   price: 'L500',
      i18n: { en: { name: 'Vanilla',                 desc: 'Warm vanilla cream, vanilla ice cream and whipped cream.' } } },
    { id: 'crepe-chocolate', slug: 'crepe-chocolate', price: 'L500',
      i18n: { en: { name: 'Chocolate',               desc: 'Warm dark chocolate sauce, chocolate ice cream and whipped cream.' } } },
  ],
}

const iceCream: MenuSection = {
  key: 'ice-cream',
  type: 'food',
  i18n: {
    en: { label: 'Ice cream' },
    sq: { label: 'Akullore' },
    it: { label: 'Gelato' },
    pl: { label: 'Lody' },
    hu: { label: 'Fagylalt' },
    de: { label: 'Eis' },
    fr: { label: 'Glaces' },
    no: { label: 'Is' },
  },
  items: [
    { id: 'banana-split',      slug: 'banana-split',      price: 'L600',
      i18n: { en: { name: 'Banana Split',      desc: 'Vanilla, chocolate and strawberry gelato · banana slices, macaroon, chocolate sauce, Chantilly cream.' } } },
    { id: 'snow-white',        slug: 'snow-white',        price: 'L500',
      i18n: { en: { name: 'Snow White',        desc: 'Vanilla gelato, chocolate sauce, macaroon, Chantilly cream.' } } },
    { id: 'pink-panther',      slug: 'pink-panther',      price: 'L500',
      i18n: { en: { name: 'Pink Panther',      desc: 'Strawberry gelato, red fruits sauce, macaroon, Chantilly cream.' } } },
    { id: 'the-green-one',     slug: 'the-green-one',     price: 'L500',
      i18n: { en: { name: 'The Green One',     desc: 'Sicilian pistachio and vanilla gelato, macaroon, crushed pistachio, Chantilly cream.' } } },
    { id: 'sundae-royale',     slug: 'sundae-royale',     price: 'L550',
      i18n: { en: { name: 'Sundae Royale',     desc: 'Waffle cones, chocolate and vanilla gelato, hazelnuts, warm chocolate, whipped cream, macaroon.' } } },
    { id: 'sundae-strawberry', slug: 'sundae-strawberry', price: 'L550',
      i18n: { en: { name: 'Sundae Strawberry', desc: 'Vanilla and strawberry gelato, red fruits sauce, crushed meringue, whipped cream, macaroon.' } } },
    { id: 'sundae-caramel',    slug: 'sundae-caramel',    price: 'L550',
      i18n: { en: { name: 'Sundae Caramel',    desc: 'Vanilla and Biscoff gelato, caramelised banana, salted caramel sauce, whipped cream, macaroon, torched marshmallow.' } } },
    { id: 'ice-cream-selection', slug: 'ice-cream-selection', price: 'L150', badge: 'Per scoop',
      i18n: { en: { name: 'Selection of Ice Cream', desc: 'Chocolate · Pistachio · Vanilla · Biscoff · Passion Fruit · Strawberry · Yogurt · Cherries.' } } },
  ],
}

export const coteMenuData: VenueMenuData = {
  sections: [hotDrinks, coldCoffees, softDrinks, bioJuices, beers, wine, cocktails],
  foodSections: [breakfast, sandwiches, salads, smallPlates, pastries, waffles, crepes, iceCream],
  pairings: [],
  foodPairings: [],
  featuredPick: { cocktailRef: '' },
}
