import type { MenuSection, VenueMenuData } from './menu-data'

// ---------------------------------------------------------------------------
// Côte Durrës — menu data
// Source: menu photo parse 2026-06-23. Prices in Albanian Lek (ALL / L).
// ⚠️ Van... / Cho... (waffles + crêpes) — photo cut off, names and prices
//    are educated guesses (same tier as Royale/Pink). Confirm with client.
// ---------------------------------------------------------------------------

const hotDrinks: MenuSection = {
  key: 'hot-drinks',
  type: 'food',
  i18n: { en: { label: 'Hot drinks' } },
  items: [
    { id: 'espresso',       slug: 'espresso',       price: 'L90',  glass: undefined,
      i18n: { en: { name: 'Espresso',                desc: '' } } },
    { id: 'macchiato',      slug: 'macchiato',      price: 'L100', glass: undefined,
      i18n: { en: { name: 'Macchiato',               desc: '' } } },
    { id: 'decaffeinato',   slug: 'decaffeinato',   price: 'L100', glass: undefined,
      i18n: { en: { name: 'Decaffeinato',            desc: '' } } },
    { id: 'latte-macchiato', slug: 'latte-macchiato', price: 'L200', glass: undefined,
      i18n: { en: { name: 'Latte Macchiato',         desc: '' } } },
    { id: 'americano',      slug: 'americano',      price: 'L100', glass: undefined,
      i18n: { en: { name: 'Americano',               desc: '' } } },
    { id: 'cappuccino',     slug: 'cappuccino',     price: 'L200', glass: undefined,
      i18n: { en: { name: 'Cappuccino',              desc: '' } } },
    { id: 'hot-chocolate',  slug: 'hot-chocolate',  price: 'L200', glass: undefined,
      i18n: { en: { name: 'Hot Chocolate',           desc: '' } } },
    { id: 'hot-tea',        slug: 'hot-tea',        price: 'L100', glass: undefined,
      i18n: { en: { name: 'Hot Tea',                 desc: '' } } },
    { id: 'bio-tea',        slug: 'bio-tea',        price: 'L150', glass: undefined,
      i18n: { en: { name: 'Bio Tea',                 desc: '' } } },
    { id: 'salep',          slug: 'salep',          price: 'L150', glass: undefined,
      i18n: { en: { name: 'Salep',                   desc: '' } } },
    { id: 'min-cacao',      slug: 'min-cacao',      price: 'L100', glass: undefined,
      i18n: { en: { name: 'Min Cacao',               desc: '' } } },
    { id: 'cacao',          slug: 'cacao',          price: 'L150', glass: undefined,
      i18n: { en: { name: 'Cacao',                   desc: '' } } },
    { id: 'irish-french-coffee', slug: 'irish-french-coffee', price: 'L450', glass: undefined,
      i18n: { en: { name: 'Irish Coffee / French Coffee', desc: '' } } },
  ],
}

const coldCoffees: MenuSection = {
  key: 'cold-coffees',
  type: 'food',
  i18n: { en: { label: 'Cold coffees' } },
  items: [
    { id: 'freddo-espresso',    slug: 'freddo-espresso',    price: 'L200', glass: undefined,
      i18n: { en: { name: 'Freddo Espresso',    desc: '' } } },
    { id: 'freddo-macchiato',   slug: 'freddo-macchiato',   price: 'L250', glass: undefined,
      i18n: { en: { name: 'Freddo Macchiato',   desc: '' } } },
    { id: 'frappe',             slug: 'frappe',             price: 'L250', glass: undefined,
      i18n: { en: { name: 'Frappé',             desc: '' } } },
    { id: 'freddo-cappuccino',  slug: 'freddo-cappuccino',  price: 'L250', glass: undefined,
      i18n: { en: { name: 'Freddo Cappuccino',  desc: '' } } },
    { id: 'freddo-chocolate',   slug: 'freddo-chocolate',   price: 'L250', glass: undefined,
      i18n: { en: { name: 'Freddo Chocolate',   desc: '' } } },
  ],
}

const softDrinks: MenuSection = {
  key: 'soft-drinks',
  type: 'food',
  i18n: { en: { label: 'Soft drinks' } },
  items: [
    { id: 'water',          slug: 'water',          price: 'L100', glass: undefined,
      i18n: { en: { name: 'Water',                   desc: '' } } },
    { id: 'bitter',         slug: 'bitter',         price: 'L100', glass: undefined,
      i18n: { en: { name: 'Bitter',                  desc: '' } } },
    { id: 'vitamins-water', slug: 'vitamins-water', price: 'L150', glass: undefined,
      i18n: { en: { name: 'Vitamins Water',          desc: '' } } },
    { id: 'energy-drink',   slug: 'energy-drink',   price: 'L250', glass: undefined,
      i18n: { en: { name: 'Energy Drink',            desc: '' } } },
    { id: 'bravo',          slug: 'bravo',          price: 'L200', glass: undefined,
      i18n: { en: { name: 'Bravo',                   desc: '' } } },
    { id: 'iced-tea',       slug: 'iced-tea',       price: 'L200', glass: undefined,
      i18n: { en: { name: 'Iced Tea',                desc: '' } } },
    { id: 'coca-cola',      slug: 'coca-cola',      price: 'L200', glass: undefined,
      i18n: { en: { name: 'Coca-Cola',               desc: '' } } },
    { id: 'fanta',          slug: 'fanta',          price: 'L200', glass: undefined,
      i18n: { en: { name: 'Fanta',                   desc: '' } } },
    { id: 'crodino',        slug: 'crodino',        price: 'L150', glass: undefined,
      i18n: { en: { name: 'Crodino',                 desc: '' } } },
    { id: 'orange-lemon-soda', slug: 'orange-lemon-soda', price: 'L200', glass: undefined,
      i18n: { en: { name: 'Orange & Lemon Soda',     desc: '' } } },
    { id: 'sprite',         slug: 'sprite',         price: 'L200', glass: undefined,
      i18n: { en: { name: 'Sprite',                  desc: '' } } },
    { id: 'tonic-water',    slug: 'tonic-water',    price: 'L200', glass: undefined,
      i18n: { en: { name: 'Tonic Water',             desc: '' } } },
    { id: 'nescafe',        slug: 'nescafe',        price: 'L200', glass: undefined,
      i18n: { en: { name: 'Nescafé',                 desc: '' } } },
    { id: 'red-bull',       slug: 'red-bull',       price: 'L350', glass: undefined,
      i18n: { en: { name: 'Red Bull',                desc: '' } } },
    { id: 'rose-lemonade',  slug: 'rose-lemonade',  price: 'L450', glass: undefined,
      i18n: { en: { name: 'Rose Lemonade',           desc: '' } } },
    { id: 'smoothie',       slug: 'smoothie',       price: 'L350', glass: undefined,
      i18n: { en: { name: 'Smoothie',                desc: '' } } },
    { id: 'milkshake',      slug: 'milkshake',      price: 'L350', glass: undefined,
      i18n: { en: { name: 'Milkshake',               desc: '' } } },
  ],
}

const bioJuices: MenuSection = {
  key: 'bio-juices',
  type: 'food',
  i18n: { en: { label: 'Bio juices' } },
  items: [
    { id: 'apple-juice-bio',  slug: 'apple-juice-bio',  price: 'L300', glass: undefined,
      i18n: { en: { name: 'Apple Juice Bio',  desc: '' } } },
    { id: 'orange-juice-bio', slug: 'orange-juice-bio', price: 'L300', glass: undefined,
      i18n: { en: { name: 'Orange Juice Bio', desc: '' } } },
    { id: 'mixed-juice-bio',  slug: 'mixed-juice-bio',  price: 'L300', glass: undefined,
      i18n: { en: { name: 'Mixed Juice Bio',  desc: '' } } },
  ],
}

const beers: MenuSection = {
  key: 'beers',
  type: 'food',
  i18n: { en: { label: 'Beers' } },
  items: [
    { id: 'beer-zero',          slug: 'beer-zero',          price: 'L250', glass: undefined,
      i18n: { en: { name: '0% Alcohol Beer',    desc: '' } } },
    { id: 'peroni',             slug: 'peroni',             price: 'L350', glass: undefined,
      i18n: { en: { name: 'Peroni',             desc: '' } } },
    { id: 'korca',              slug: 'korca',              price: 'L350', glass: undefined,
      i18n: { en: { name: 'Korça',              desc: '' } } },
    { id: 'heineken',           slug: 'heineken',           price: 'L400', glass: undefined,
      i18n: { en: { name: 'Heineken',           desc: '' } } },
    { id: 'corona',             slug: 'corona',             price: 'L350', glass: undefined,
      i18n: { en: { name: 'Corona',             desc: '' } } },
    { id: 'paulaner-kristall',  slug: 'paulaner-kristall',  price: 'L450', glass: undefined,
      i18n: { en: { name: 'Paulaner Kristall',  desc: '' } } },
    { id: 'paulaner-weissbier', slug: 'paulaner-weissbier', price: 'L450', glass: undefined,
      i18n: { en: { name: 'Paulaner Weissbier', desc: '' } } },
  ],
}

const wine: MenuSection = {
  key: 'wine',
  type: 'food',
  i18n: { en: { label: 'Wine & Prosecco', sub: '125 ml · Bottle 2,500' } },
  items: [
    { id: 'prosecco',           slug: 'prosecco',           price: 'L450', glass: undefined,
      i18n: { en: { name: 'Prosecco',           desc: '' } } },
    { id: 'pinot-grigio',       slug: 'pinot-grigio',       price: 'L450', glass: undefined,
      i18n: { en: { name: 'Pinot Grigio',       desc: '' } } },
    { id: 'pinot-grigio-blush', slug: 'pinot-grigio-blush', price: 'L450', glass: undefined,
      i18n: { en: { name: 'Pinot Grigio Blush', desc: '' } } },
    { id: 'merlot',             slug: 'merlot',             price: 'L450', glass: undefined,
      i18n: { en: { name: 'Merlot',             desc: '' } } },
  ],
}

const cocktails: MenuSection = {
  key: 'cocktails',
  type: 'food',
  i18n: { en: { label: 'Cocktails', note: 'Any 2 of the same · 1,200' } },
  items: [
    { id: 'cote-mojito',          slug: 'cote-mojito',          price: 'L700', glass: undefined,
      i18n: { en: { name: 'Mojito',             desc: 'White rum, fresh lime and mint, soda water and brown sugar.' } } },
    { id: 'cote-margarita',       slug: 'cote-margarita',       price: 'L700', glass: undefined,
      i18n: { en: { name: 'Margarita',          desc: 'Tequila, triple sec, lime juice.' } } },
    { id: 'cote-sex-beach',       slug: 'cote-sex-beach',       price: 'L700', glass: undefined,
      i18n: { en: { name: 'Sex on the Beach',   desc: 'Peach schnapps, vodka, orange juice and grenadine.' } } },
    { id: 'cote-pina-colada',     slug: 'cote-pina-colada',     price: 'L700', glass: undefined,
      i18n: { en: { name: 'Piña Colada',        desc: 'White rum, coconut cream, fresh pineapple and Malibu.' } } },
    { id: 'cote-pornstar-martini',slug: 'cote-pornstar-martini',price: 'L700', glass: undefined,
      i18n: { en: { name: 'Pornstar Martini',   desc: 'Vanilla vodka, vanilla syrup, passion fruit, fresh lime and a shot of prosecco.' } } },
    { id: 'cote-espresso-martini',slug: 'cote-espresso-martini',price: 'L700', glass: undefined,
      i18n: { en: { name: 'Espresso Martini',   desc: 'Kahlúa, espresso coffee and vodka.' } } },
    { id: 'cote-negroni',         slug: 'cote-negroni',         price: 'L700', glass: undefined,
      i18n: { en: { name: 'Negroni',            desc: 'Gin, Campari, Martini Rosso and a slice of fresh orange.' } } },
    { id: 'cote-tequila-sunrise', slug: 'cote-tequila-sunrise', price: 'L700', glass: undefined,
      i18n: { en: { name: 'Tequila Sunrise',    desc: 'Grenadine, tequila and Cointreau, blend of orange and lemon juice, topped with a cherry.' } } },
    { id: 'cote-amaretto-sour',   slug: 'cote-amaretto-sour',   price: 'L700', glass: undefined,
      i18n: { en: { name: 'Amaretto Sour',      desc: 'Disaronno shaken with lemon juice, topped with egg white and a cherry.' } } },
    { id: 'cote-long-island',     slug: 'cote-long-island',     price: 'L700', glass: undefined,
      i18n: { en: { name: 'Long Island Iced Tea', desc: 'Vodka, white rum, gin, triple sec, lime juice and Coke.' } } },
    { id: 'cote-aperol-spritz',   slug: 'cote-aperol-spritz',   price: 'L700', glass: undefined,
      i18n: { en: { name: 'Aperol Spritz',      desc: 'Aperol, prosecco and soda water.' } } },
    { id: 'cote-whiskey-sour',    slug: 'cote-whiskey-sour',    price: 'L700', glass: undefined,
      i18n: { en: { name: 'Whiskey Sour',       desc: 'Whiskey shaken with lemon juice, topped with egg white and a cherry.' } } },
    { id: 'cote-strawberry-punch',slug: 'cote-strawberry-punch',price: 'L700', glass: undefined,
      i18n: { en: { name: 'Strawberry Punch',   desc: 'Pink gin, prosecco, grenadine and fresh strawberries.' } } },
    { id: 'cote-zombie',          slug: 'cote-zombie',          price: 'L900', glass: undefined, badge: 'Double 1,600',
      i18n: { en: { name: 'Zombie',             desc: 'Gold and white rum, orange liquor, lime, vanilla syrup and pineapple juice.' } } },
  ],
}

const breakfast: MenuSection = {
  key: 'breakfast',
  type: 'food',
  i18n: { en: {
    label: 'Breakfast',
    sub: 'Until 3 pm',
    note: '+ extras: Sausage 100 · Meatballs 100 · Avocado 200 · Bacon 100 · Cheese 150 · Hollandaise Sauce 150',
  } },
  items: [
    { id: 'fruit-salad',    slug: 'fruit-salad',    price: 'L500', glass: undefined,
      i18n: { en: { name: 'Fruit Salad',             desc: 'Mixed seasonal fruits.' } } },
    { id: 'granola-yogurt', slug: 'granola-yogurt', price: 'L550', glass: undefined,
      i18n: { en: { name: 'Granola & Greek Yogurt',  desc: 'Greek yogurt, granola, fresh fruits.' } } },
    { id: 'crepe-complete', slug: 'crepe-complete', price: 'L650', glass: undefined,
      i18n: { en: { name: 'Crêpe Complete',          desc: 'Crêpe with ham, cheese and egg.' } } },
    { id: 'bacon-sausage-breakfast', slug: 'bacon-sausage-breakfast', price: 'L700', glass: undefined,
      i18n: { en: { name: 'Bacon & Sausage Breakfast', desc: 'Toasted bread, scrambled eggs, cheese, sausage, bacon, fresh tomato.' } } },
    { id: 'smoked-salmon-breakfast', slug: 'smoked-salmon-breakfast', price: 'L800', glass: undefined,
      i18n: { en: { name: 'Smoked Salmon Breakfast', desc: 'Toasted bread, scrambled eggs, cheese, smoked salmon.' } } },
    { id: 'vegetarian-breakfast', slug: 'vegetarian-breakfast', price: 'L600', glass: undefined,
      i18n: { en: { name: 'Vegetarian Breakfast',   desc: 'Toasted bread, scrambled eggs, cheese, fresh fruits.' } } },
    { id: 'omelette-ham-cheese', slug: 'omelette-ham-cheese', price: 'L600', glass: undefined,
      i18n: { en: { name: 'Omelette with Ham & Cheese', desc: 'Served with toast.' } } },
    { id: 'french-toast',   slug: 'french-toast',   price: 'L600', glass: undefined,
      i18n: { en: { name: 'French Toast',           desc: 'Toasted brioche, seasonal fruits, honey, Greek yogurt.' } } },
    { id: 'french-toast-platter', slug: 'french-toast-platter', price: 'L850', glass: undefined,
      i18n: { en: { name: 'French Toast Platter',  desc: 'Toasted brioche, seasonal fruits, honey, scrambled eggs and bacon.' } } },
  ],
}

const sandwiches: MenuSection = {
  key: 'sandwiches',
  type: 'food',
  i18n: { en: { label: 'Sandwiches', sub: 'Until 3 pm' } },
  items: [
    { id: 'ham-cheese-sandwich',  slug: 'ham-cheese-sandwich',  price: 'L250', glass: undefined,
      i18n: { en: { name: 'Ham & Cheese',        desc: 'Ham, cheese and mayonnaise.' } } },
    { id: 'tuna-sandwich',        slug: 'tuna-sandwich',        price: 'L350', glass: undefined,
      i18n: { en: { name: 'Tuna',                desc: 'Mayonnaise, red onion, sweetcorn and rocket.' } } },
    { id: 'vegetarian-sandwich',  slug: 'vegetarian-sandwich',  price: 'L250', glass: undefined,
      i18n: { en: { name: 'Vegetarian',          desc: 'Lettuce, tomato, cucumber and mayonnaise.' } } },
    { id: 'meatball-sandwich',    slug: 'meatball-sandwich',    price: 'L250', glass: undefined,
      i18n: { en: { name: 'Meatball',            desc: 'Meatballs and tzatziki.' } } },
  ],
}

const salads: MenuSection = {
  key: 'salads',
  type: 'food',
  i18n: { en: { label: 'Salads' } },
  items: [
    { id: 'caprese-salad',        slug: 'caprese-salad',        price: 'L550', glass: undefined,
      i18n: { en: { name: 'Caprese',             desc: 'Tomato and mozzarella.' } } },
    { id: 'greek-salad',          slug: 'greek-salad',          price: 'L500', glass: undefined,
      i18n: { en: { name: 'Greek Salad',         desc: 'Tomato, cucumber, olives and onion.' } } },
    { id: 'caesar-chicken',       slug: 'caesar-chicken',       price: 'L800', glass: undefined,
      i18n: { en: { name: 'Caesar with Chicken', desc: 'Lettuce, Caesar dressing, egg, croutons, chicken breast.' } } },
  ],
}

const smallPlates: MenuSection = {
  key: 'small-plates',
  type: 'food',
  i18n: { en: {
    label: 'Small plates',
    note: 'Any 3 for 1,500 · Sauce +150: Tzatziki / Pepper Salsa / BBQ / Garlic Mayo',
  } },
  items: [
    { id: 'bread-olives',        slug: 'bread-olives',        price: 'L400', glass: undefined,
      i18n: { en: { name: 'Bread & Olives',                    desc: '' } } },
    { id: 'bruschetta-pomodoro', slug: 'bruschetta-pomodoro', price: 'L400', glass: undefined,
      i18n: { en: { name: 'Bruschetta Pomodoro',               desc: '' } } },
    { id: 'sp-greek-salad',      slug: 'sp-greek-salad',      price: 'L400', glass: undefined,
      i18n: { en: { name: 'Greek Salad',                       desc: '' } } },
    { id: 'sp-caesar-salad',     slug: 'sp-caesar-salad',     price: 'L400', glass: undefined,
      i18n: { en: { name: 'Caesar Salad',                      desc: '' } } },
    { id: 'garlic-prawns',       slug: 'garlic-prawns',       price: 'L400', glass: undefined,
      i18n: { en: { name: 'Garlic Prawns',                     desc: '' } } },
    { id: 'meatballs-tomato',    slug: 'meatballs-tomato',    price: 'L400', glass: undefined,
      i18n: { en: { name: 'Meatballs in Tomato Sauce',         desc: '' } } },
    { id: 'seafood-garlic-tomato', slug: 'seafood-garlic-tomato', price: 'L400', glass: undefined,
      i18n: { en: { name: 'Seafood Mix in Garlic & Fresh Tomato', desc: '' } } },
    { id: 'paprika-potatoes',    slug: 'paprika-potatoes',    price: 'L400', glass: undefined,
      i18n: { en: { name: 'Paprika Potatoes',                  desc: '' } } },
    { id: 'spanish-omelette',    slug: 'spanish-omelette',    price: 'L400', glass: undefined,
      i18n: { en: { name: 'Spanish Omelette',                  desc: '' } } },
    { id: 'spicy-sausage',       slug: 'spicy-sausage',       price: 'L400', glass: undefined,
      i18n: { en: { name: 'Spicy Sausage',                     desc: '' } } },
    { id: 'cassoulet-lamb',      slug: 'cassoulet-lamb',      price: 'L400', glass: undefined,
      i18n: { en: { name: 'Cassoulet with Lamb',               desc: '' } } },
    { id: 'asian-beef',          slug: 'asian-beef',          price: 'L400', glass: undefined,
      i18n: { en: { name: 'Asian Beef',                        desc: '' } } },
    { id: 'salmon-lemon',        slug: 'salmon-lemon',        price: 'L800', glass: undefined, badge: '+400 surcharge',
      i18n: { en: { name: 'Salmon Fillet with Lemon',          desc: '' } } },
    { id: 'chicken-strips',      slug: 'chicken-strips',      price: 'L400', glass: undefined,
      i18n: { en: { name: 'Chicken Strips',                    desc: '' } } },
    { id: 'grilled-peppers',     slug: 'grilled-peppers',     price: 'L400', glass: undefined,
      i18n: { en: { name: 'Grilled Peppers',                   desc: '' } } },
    { id: 'steamed-veg',         slug: 'steamed-veg',         price: 'L400', glass: undefined,
      i18n: { en: { name: 'Steamed Vegetables with Olive Oil', desc: '' } } },
    { id: 'rice',                slug: 'rice',                price: 'L400', glass: undefined,
      i18n: { en: { name: 'Rice',                              desc: '' } } },
  ],
}

const pastries: MenuSection = {
  key: 'pastries',
  type: 'food',
  i18n: { en: { label: 'Pastries' } },
  items: [
    { id: 'croissants',    slug: 'croissants',    price: 'L150', glass: undefined,
      i18n: { en: { name: 'Selection of Croissants', desc: 'Chocolate · Pistachio · Crème.' } } },
    { id: 'pastry-selection', slug: 'pastry-selection', price: 'L300', glass: undefined,
      i18n: { en: { name: 'Selection of Pastries', desc: 'Snickers · Kinder · Lemon · Cipriani · Lacta · Amanda.' } } },
    { id: 'cheesecake',    slug: 'cheesecake',    price: 'L280', glass: undefined,
      i18n: { en: { name: 'Cheesecake',           desc: '' } } },
    { id: 'kamelia-lotus', slug: 'kamelia-lotus', price: 'L320', glass: undefined,
      i18n: { en: { name: 'Kamelia – Lotus',      desc: '' } } },
    { id: 'ekmek-tiramisu',slug: 'ekmek-tiramisu',price: 'L250', glass: undefined,
      i18n: { en: { name: 'Ekmek – Tiramisu',     desc: '' } } },
    { id: 'pastashu',      slug: 'pastashu',      price: 'L180', glass: undefined,
      i18n: { en: { name: 'Pastashu',             desc: '' } } },
    { id: 'zup',           slug: 'zup',           price: 'L220', glass: undefined,
      i18n: { en: { name: 'Zup',                  desc: '' } } },
    { id: 'cannoli',       slug: 'cannoli',        price: 'L180', glass: undefined,
      i18n: { en: { name: 'Cannoli',              desc: '' } } },
  ],
}

const waffles: MenuSection = {
  key: 'waffles',
  type: 'food',
  i18n: { en: { label: 'Waffles' } },
  items: [
    { id: 'waffle-dubai',    slug: 'waffle-dubai',    price: 'L850', glass: undefined,
      i18n: { en: { name: 'Dubai',              desc: 'Nutella, pistachio sauce, kadaif and pistachio ice cream.' } } },
    { id: 'waffle-royale',   slug: 'waffle-royale',   price: 'L550', glass: undefined,
      i18n: { en: { name: 'Royale',             desc: 'Nutella, hazelnuts, hazelnut chocolate truffle, chocolate ice cream and whipped cream.' } } },
    { id: 'waffle-pink',     slug: 'waffle-pink',     price: 'L550', glass: undefined,
      i18n: { en: { name: 'Pink',               desc: 'Warm white chocolate sauce, chocolate shavings, strawberry ice cream and whipped cream.' } } },
    { id: 'waffle-pistachio',slug: 'waffle-pistachio',price: 'L600', glass: undefined,
      i18n: { en: { name: 'Pistachio',          desc: 'Warm milk and white chocolate sauce, crushed pistachio, pistachio ice cream and whipped cream.' } } },
    { id: 'waffle-lotus',    slug: 'waffle-lotus',    price: 'L550', glass: undefined,
      i18n: { en: { name: 'Lotus',              desc: 'Warm Lotus sauce, crushed lotus biscuits, Lotus ice cream and whipped cream.' } } },
    { id: 'waffle-banana',   slug: 'waffle-banana',   price: 'L550', glass: undefined,
      i18n: { en: { name: 'Banana',             desc: 'Warm caramel and white chocolate sauce, banana, torched marshmallows, vanilla ice cream and whipped cream.' } } },
    { id: 'waffle-passion',  slug: 'waffle-passion',  price: 'L550', glass: undefined,
      i18n: { en: { name: 'Passion Fruit & Pineapple', desc: 'Caramel sauce, caramelised cinnamon pineapple, hazelnuts, passion fruit ice cream and cream.' } } },
    { id: 'waffle-flambee',  slug: 'waffle-flambee',  price: 'L750', glass: undefined,
      i18n: { en: { name: 'Flambée',            desc: 'Fresh orange juice, fresh orange, Grand Marnier, vanilla ice cream and whipped cream.' } } },
    // TODO: confirm name and price (photo cut off right edge)
    { id: 'waffle-vanilla',  slug: 'waffle-vanilla',  price: 'L550', glass: undefined,
      i18n: { en: { name: 'Vanilla',            desc: '' } } },
    { id: 'waffle-chocolate',slug: 'waffle-chocolate',price: 'L550', glass: undefined,
      i18n: { en: { name: 'Chocolate',          desc: '' } } },
  ],
}

const crepes: MenuSection = {
  key: 'crepes',
  type: 'food',
  i18n: { en: { label: 'Crêpes' } },
  items: [
    { id: 'crepe-dubai',    slug: 'crepe-dubai',    price: 'L800', glass: undefined,
      i18n: { en: { name: 'Dubai',              desc: 'Nutella, pistachio sauce, kadaif and pistachio ice cream.' } } },
    { id: 'crepe-royale',   slug: 'crepe-royale',   price: 'L500', glass: undefined,
      i18n: { en: { name: 'Royale',             desc: 'Nutella, hazelnuts, hazelnut chocolate truffle, chocolate ice cream and whipped cream.' } } },
    { id: 'crepe-pink',     slug: 'crepe-pink',     price: 'L500', glass: undefined,
      i18n: { en: { name: 'Pink',               desc: 'Warm white chocolate sauce, chocolate shavings, strawberry ice cream and whipped cream.' } } },
    { id: 'crepe-pistachio',slug: 'crepe-pistachio',price: 'L550', glass: undefined,
      i18n: { en: { name: 'Pistachio',          desc: 'Warm milk and white chocolate sauce, crushed pistachio, pistachio ice cream and whipped cream.' } } },
    { id: 'crepe-lotus',    slug: 'crepe-lotus',    price: 'L500', glass: undefined,
      i18n: { en: { name: 'Lotus',              desc: 'Warm Lotus sauce, crushed lotus biscuits, Lotus ice cream and whipped cream.' } } },
    { id: 'crepe-banana',   slug: 'crepe-banana',   price: 'L500', glass: undefined,
      i18n: { en: { name: 'Banana',             desc: 'Warm caramel and white chocolate sauce, banana, torched marshmallows, vanilla ice cream and whipped cream.' } } },
    { id: 'crepe-passion',  slug: 'crepe-passion',  price: 'L500', glass: undefined,
      i18n: { en: { name: 'Passion Fruit & Pineapple', desc: 'Caramel sauce, caramelised cinnamon pineapple, hazelnuts, passion fruit ice cream and cream.' } } },
    { id: 'crepe-flambee',  slug: 'crepe-flambee',  price: 'L700', glass: undefined,
      i18n: { en: { name: 'Flambée',            desc: 'Fresh orange juice, fresh orange, Grand Marnier, vanilla ice cream and whipped cream.' } } },
    // TODO: confirm name and price (photo cut off right edge)
    { id: 'crepe-vanilla',  slug: 'crepe-vanilla',  price: 'L500', glass: undefined,
      i18n: { en: { name: 'Vanilla',            desc: '' } } },
    { id: 'crepe-chocolate',slug: 'crepe-chocolate',price: 'L500', glass: undefined,
      i18n: { en: { name: 'Chocolate',          desc: '' } } },
  ],
}

const iceCream: MenuSection = {
  key: 'ice-cream',
  type: 'food',
  i18n: { en: { label: 'Ice cream' } },
  items: [
    { id: 'banana-split',     slug: 'banana-split',     price: 'L600', glass: undefined,
      i18n: { en: { name: 'Banana Split',     desc: 'Vanilla, chocolate and strawberry gelato · banana slices, macaroon, chocolate sauce, Chantilly cream.' } } },
    { id: 'snow-white',       slug: 'snow-white',       price: 'L500', glass: undefined,
      i18n: { en: { name: 'Snow White',       desc: 'Vanilla gelato, chocolate sauce, macaroon, Chantilly cream.' } } },
    { id: 'pink-panther',     slug: 'pink-panther',     price: 'L500', glass: undefined,
      i18n: { en: { name: 'Pink Panther',     desc: 'Strawberry gelato, red fruits sauce, macaroon, Chantilly cream.' } } },
    { id: 'the-green-one',    slug: 'the-green-one',    price: 'L500', glass: undefined,
      i18n: { en: { name: 'The Green One',    desc: 'Sicilian pistachio and vanilla gelato, macaroon, crushed pistachio, Chantilly cream.' } } },
    { id: 'sundae-royale',    slug: 'sundae-royale',    price: 'L550', glass: undefined,
      i18n: { en: { name: 'Sundae Royale',    desc: 'Waffle cones, chocolate and vanilla gelato, hazelnuts, warm chocolate, whipped cream, macaroon.' } } },
    { id: 'sundae-strawberry',slug: 'sundae-strawberry',price: 'L550', glass: undefined,
      i18n: { en: { name: 'Sundae Strawberry',desc: 'Vanilla and strawberry gelato, red fruits sauce, crushed meringue, whipped cream, macaroon.' } } },
    { id: 'sundae-caramel',   slug: 'sundae-caramel',   price: 'L550', glass: undefined,
      i18n: { en: { name: 'Sundae Caramel',   desc: 'Vanilla and Biscoff gelato, caramelised banana, salted caramel sauce, whipped cream, macaroon, torched marshmallow.' } } },
    { id: 'ice-cream-selection', slug: 'ice-cream-selection', price: 'L150', glass: undefined, badge: 'Per scoop',
      i18n: { en: { name: 'Selection of Ice Cream', desc: 'Chocolate · Pistachio · Vanilla · Biscoff · Passion Fruit · Strawberry · Yogurt · Cherries.' } } },
  ],
}

export const coteMenuData: VenueMenuData = {
  sections: [],
  foodSections: [
    hotDrinks, coldCoffees, softDrinks, bioJuices,
    beers, wine, cocktails,
    breakfast, sandwiches, salads, smallPlates,
    pastries, waffles, crepes, iceCream,
  ],
  pairings: [],
  foodPairings: [],
  featuredPick: { cocktailRef: '' },
}
